export type ChileProduct = {
  slug: string; name: string; title: string; description: string; processRole: string; driveType: string;
  contexts: string[]; selectionInputs: string[]; verifiedSpecifications: [string, string][]; faq: [string, string][]; relatedSolutions: string[];
};

export const chileProducts: ChileProduct[] = [
  { slug: "sistema-bomba-incendio-edj", name: "Sistema de bomba contra incendio EDJ", title: "Sistema EDJ para proyectos contra incendio en Chile", description: "Configuración que reúne una bomba eléctrica, una bomba diésel y una bomba jockey para revisar la continuidad de bombeo según el proyecto.", processRole: "Integra impulsión eléctrica, respaldo diésel y mantenimiento de presión en una misma conversación técnica.", driveType: "Eléctrico + diésel + jockey", contexts: ["Bodegas y centros de distribución", "Plantas industriales", "Infraestructura con requisitos de respaldo"], selectionInputs: ["Caudal y presión requeridos", "Disponibilidad eléctrica y diésel", "Plano de sala de bombas y fuente de agua", "Norma o requisito del proyecto"], verifiedSpecifications: [["Configuración", "Eléctrica + diésel + jockey"], ["Selección", "Se confirma para el proyecto"], ["Documentación", "Solicite la ficha aplicable"]], faq: [["¿Cuándo se revisa un sistema EDJ?", "Cuando el proyecto necesita analizar una combinación de accionamiento eléctrico, diésel y jockey."], ["¿Qué información se necesita?", "Caudal, presión, energía disponible, fuente de agua, plano y requisitos del proyecto."]], relatedSolutions: ["bombas-contra-incendio-bodegas", "bombas-contra-incendio-plantas-industriales", "bombas-contra-incendio-centros-datos"] },
  { slug: "bomba-diesel-contra-incendio", name: "Bomba diésel contra incendio", title: "Bomba diésel contra incendio para proyectos en Chile", description: "Alternativa para revisar cuando el proyecto requiere una fuente de accionamiento diésel o se ubica en un entorno con condiciones eléctricas a confirmar.", processRole: "Aporta una opción de accionamiento diésel dentro del análisis de la sala de bombas y del respaldo requerido.", driveType: "Diésel + jockey (según configuración)", contexts: ["Zonas remotas", "Petróleo, gas y logística de sitio", "Proyectos con respaldo a revisar"], selectionInputs: ["Condiciones ambientales y de instalación", "Disponibilidad y gestión de combustible", "Caudal, presión y fuente de agua", "Documentos del proyecto"], verifiedSpecifications: [["Accionamiento", "Diésel según configuración"], ["Mantenimiento", "Se define con la documentación del proyecto"], ["Parámetros", "Se confirma para el proyecto"]], faq: [["¿Qué se debe confirmar primero?", "El entorno, los requisitos de combustible, la fuente de agua y las condiciones de operación del proyecto."], ["¿Incluye certificaciones específicas?", "Solo se deben confirmar contra documentación verificable del modelo y alcance solicitado."]], relatedSolutions: ["bombas-contra-incendio-petroleo-gas", "bombas-contra-incendio-bodegas"] },
  { slug: "bomba-electrica-contra-incendio", name: "Bomba eléctrica contra incendio", title: "Bomba eléctrica contra incendio para proyectos en Chile", description: "Configuración para proyectos con alimentación eléctrica definida y necesidades de control que deben revisarse con la ingeniería del proyecto.", processRole: "Permite organizar la revisión de alimentación, control y requerimientos de bombeo antes de definir una configuración.", driveType: "Eléctrico + jockey (según configuración)", contexts: ["Plantas industriales", "Centros de datos", "Edificios e infraestructura con energía definida"], selectionInputs: ["Datos de alimentación eléctrica", "Caudal y presión", "Requisitos de control", "Plano y condiciones de instalación"], verifiedSpecifications: [["Accionamiento", "Eléctrico según configuración"], ["Control", "Se confirma para el proyecto"], ["Datos técnicos", "Solicite ficha aplicable"]], faq: [["¿Qué datos eléctricos se requieren?", "La información disponible de alimentación y los requisitos de control del proyecto."], ["¿Se puede definir sin caudal y presión?", "No; esos datos son necesarios para revisar la configuración."]], relatedSolutions: ["bombas-contra-incendio-plantas-industriales", "bombas-contra-incendio-centros-datos"] },
  { slug: "bomba-jockey-contra-incendio", name: "Bomba jockey para incendio", title: "Bomba jockey para sistemas contra incendio", description: "Elemento orientado a mantener la presión del sistema entre las condiciones definidas para el proyecto y la lógica de control aplicable.", processRole: "Ayuda a revisar el mantenimiento de presión y su relación con las bombas principales dentro del sistema.", driveType: "Jockey", contexts: ["Sistemas EDJ", "Configuraciones eléctricas", "Configuraciones diésel"], selectionInputs: ["Presión de mantenimiento", "Relación con la bomba principal", "Lógica de control", "Datos hidráulicos del sistema"], verifiedSpecifications: [["Función", "Mantenimiento de presión del sistema"], ["Ajustes", "Se confirman para el proyecto"], ["Integración", "Se revisa con la bomba principal"]], faq: [["¿La jockey reemplaza a la bomba principal?", "No; su función debe revisarse como parte de la estrategia de mantenimiento de presión."], ["¿Qué datos son necesarios?", "Presiones objetivo, información hidráulica y la configuración de las bombas principales."]], relatedSolutions: ["bombas-contra-incendio-bodegas", "bombas-contra-incendio-plantas-industriales"] },
  { slug: "bomba-incendio-eje-largo", name: "Bomba contra incendio de eje largo", title: "Bomba de eje largo contra incendio para toma de agua", description: "Alternativa para analizar cuando la fuente de agua, la toma o las condiciones de instalación requieren una configuración de eje largo.", processRole: "Centra la revisión en la fuente de agua, el arreglo de instalación y las condiciones físicas del sitio.", driveType: "Eléctrico o diésel según configuración", contexts: ["Tomas de agua", "Condiciones de nivel a revisar", "Sitios remotos"], selectionInputs: ["Datos de la fuente de agua", "Nivel, geometría y plano de instalación", "Caudal y presión", "Condiciones ambientales"], verifiedSpecifications: [["Aplicación", "Toma de agua según proyecto"], ["Accionamiento", "Se confirma para el proyecto"], ["Instalación", "Requiere datos de sitio"]], faq: [["¿Qué profundidad puede alcanzar?", "No se publica una cifra fija: depende de la toma, la configuración y las condiciones del proyecto."], ["¿Qué se debe enviar para revisión?", "Plano de instalación, información de la fuente de agua, caudal, presión y condiciones del sitio."]], relatedSolutions: ["bombas-contra-incendio-petroleo-gas"] },
];

export type ChileSolution = { slug: string; name: string; title: string; intro: string; challenge: string; deployment: string; inputs: string[]; products: string[]; faq: [string, string][] };
export const chileSolutions: ChileSolution[] = [
  { slug: "bombas-contra-incendio-bodegas", name: "Bodegas y logística", title: "Bombas contra incendio para bodegas y logística", intro: "Guía para preparar una conversación técnica sobre sistemas de bombeo en bodegas, centros de distribución y operaciones logísticas en Chile.", challenge: "La revisión suele involucrar continuidad de operación, distribución del edificio, fuente de agua y documentación del proyecto.", deployment: "Se revisan las configuraciones de bombeo, la sala de bombas, el accionamiento disponible y los requisitos del proyecto antes de proponer una alternativa.", inputs: ["Plano o esquema de instalación", "Caudal y presión requeridos", "Fuente de agua", "Etapa de expansión o cambios previstos"], products: ["sistema-bomba-incendio-edj", "bomba-jockey-contra-incendio"], faq: [["¿Qué conviene preparar?", "Los planos disponibles, caudal, presión, fuente de agua y los documentos del proyecto."]] },
  { slug: "bombas-contra-incendio-plantas-industriales", name: "Plantas industriales", title: "Bombas contra incendio para plantas industriales", intro: "Contenido de apoyo para proyectos industriales que necesitan ordenar variables de bombeo, condiciones de instalación y documentación técnica.", challenge: "Las condiciones de proceso, el entorno y la continuidad de la planta requieren que la selección se base en información del sitio.", deployment: "La revisión conecta necesidades hidráulicas, accionamiento, sala de bombas y documentación de proyecto sin asumir condiciones no verificadas.", inputs: ["Uso y entorno de instalación", "Caudal y presión", "Alimentación disponible", "Planos y requisitos técnicos"], products: ["sistema-bomba-incendio-edj", "bomba-electrica-contra-incendio", "bomba-jockey-contra-incendio"], faq: [["¿Se publican parámetros fijos?", "Los valores deben confirmarse con los documentos y condiciones de cada proyecto."]] },
  { slug: "bombas-contra-incendio-centros-datos", name: "Centros de datos", title: "Bombas contra incendio para centros de datos", intro: "Punto de partida para proyectos de infraestructura crítica que necesitan coordinar documentación, accionamiento y variables de selección.", challenge: "La coordinación de ingeniería, la información disponible y los requisitos del proyecto deben revisarse antes de definir un sistema.", deployment: "Se organiza la conversación sobre alimentación, respaldo a evaluar, controles, fuente de agua y documentación técnica.", inputs: ["Requisitos de ingeniería", "Datos eléctricos disponibles", "Caudal, presión y fuente de agua", "Planos y coordinación de sala"], products: ["sistema-bomba-incendio-edj", "bomba-electrica-contra-incendio"], faq: [["¿Se garantiza disponibilidad?", "No se hacen promesas de disponibilidad: se revisan los requisitos documentados del proyecto."]] },
  { slug: "bombas-contra-incendio-petroleo-gas", name: "Petróleo, gas y zonas remotas", title: "Bombas contra incendio para petróleo, gas y zonas remotas", intro: "Guía para recopilar información de proyectos con condiciones remotas, ambientales o logísticas que requieren una revisión técnica específica.", challenge: "Las condiciones ambientales, la logística y la energía disponible pueden modificar la configuración a estudiar.", deployment: "Se revisan accionamiento, fuente de agua, combustibles, disposición de sitio y documentación de proyecto sin declarar certificaciones no verificadas.", inputs: ["Ubicación y condiciones ambientales", "Fuente de agua", "Datos de energía y combustible", "Planos, logística y requisitos documentados"], products: ["bomba-diesel-contra-incendio", "bomba-incendio-eje-largo"], faq: [["¿La solución incluye certificación especial?", "Solo se puede confirmar una certificación concreta con documentación válida del producto y proyecto."]] },
];

export const trustPages: Record<string, { title: string; eyebrow: string; intro: string; sections: [string, string][] }> = {
  empresa: { eyebrow: "EMPRESA", title: "GRIMM PUMP para proyectos en Chile", intro: "GRIMM PUMP es la marca de exportación de Grimm Water Treatment (Zhejiang) Co., Ltd. para compradores que necesitan una conversación técnica clara sobre sistemas de bombeo contra incendio.", sections: [["Alcance", "Atendemos consultas para proyectos en Chile y otros mercados de Latinoamérica desde una operación de exportación; esta página no declara una oficina local chilena."], ["Cómo trabajamos", "La configuración se revisa con caudal, presión, fuente de agua, accionamiento, planos y documentos disponibles."], ["Contacto", "Use los canales de contacto publicados para compartir la información de proyecto."]] },
  fabrica: { eyebrow: "INFORMACIÓN DE FABRICACIÓN", title: "Documentación de fabricación según proyecto", intro: "La información de fabricación y las imágenes deben corresponder a material verificable. Para un proyecto concreto, solicite la documentación disponible.", sections: [["Material verificable", "No se publican imágenes de fábrica ni cifras de capacidad sin una fuente interna que pueda verificarse."], ["Solicitud de información", "Indique el sistema y la aplicación para revisar qué documentación puede compartirse."]] },
  pruebas: { eyebrow: "PRUEBAS", title: "Información de pruebas con alcance verificable", intro: "La evidencia de pruebas debe revisarse contra el modelo, la configuración y el alcance real del proyecto.", sections: [["Alcance", "No se publican resultados, videos ni indicadores sin documentación verificable."], ["Siguiente paso", "Comparta el producto y los requisitos del proyecto para solicitar la información aplicable."]] },
  certificados: { eyebrow: "CERTIFICADOS", title: "Certificados y documentación verificable", intro: "Solo deben compartirse certificados con alcance, vigencia y relación de producto comprobables.", sections: [["Criterio de publicación", "No se listan normas, certificados ni aprobaciones sin documentos que permitan verificar su aplicabilidad."], ["Solicitud", "Solicite documentación indicando el producto, el mercado y el requisito del proyecto."]] },
  proyectos: { eyebrow: "PROYECTOS", title: "Información de proyectos con autorización", intro: "Los proyectos solo se publican cuando existe autorización y datos verificables para hacerlo.", sections: [["Privacidad y evidencia", "No inventamos casos, clientes, ubicaciones ni resultados de proyectos."], ["Consulta", "Para revisar experiencia relevante, comparta el tipo de instalación y los requisitos del proyecto."]] },
  descargas: { eyebrow: "DESCARGAS", title: "Solicite documentación técnica", intro: "Los catálogos, fichas y documentos de selección deben corresponder al producto y a la versión aplicable.", sections: [["Documentos", "Solicite catálogo, datos técnicos o información de configuración indicando el sistema requerido."], ["Control de versión", "Los documentos publicados o compartidos deben incluir producto, idioma, versión y fecha cuando estén disponibles."]] },
  guias: { eyebrow: "GUÍAS", title: "Guías para preparar una consulta técnica", intro: "Material de apoyo para ordenar la información que un equipo de ingeniería o compras puede preparar antes de solicitar una revisión.", sections: [["Información de selección", "Caudal, presión, fuente de agua, accionamiento, planos, condiciones de instalación y requisitos del proyecto."], ["Uso responsable", "La guía no sustituye la ingeniería, las normas aplicables ni la validación específica de un proyecto."]] },
  contacto: { eyebrow: "CONTACTO", title: "Cuéntenos sobre su proyecto", intro: "Comparta la información disponible de su proyecto en Chile para iniciar una revisión de configuración y documentación.", sections: [] },
  "politica-de-privacidad": { eyebrow: "PRIVACIDAD", title: "Política de privacidad", intro: "Esta página explica el uso de los datos enviados mediante el formulario de consulta.", sections: [["Datos recogidos", "El formulario recoge datos de contacto y de proyecto necesarios para responder la solicitud."], ["Uso", "Los datos se usan para atender la consulta y no se incluyen en la URL pública."], ["Contacto", "Puede utilizar los canales de contacto del sitio para consultas sobre sus datos."]] },
};
