export type ChileProduct = {
  slug: string; name: string; title: string; description: string; processRole: string; driveType: string;
  category?: string; sourceProductSlug?: string; contexts: string[]; selectionInputs: string[]; verifiedSpecifications: [string, string][]; faq: [string, string][]; relatedSolutions: string[];
};

export const legacyChileProducts: ChileProduct[] = [
  { slug: "sistema-bomba-incendio-edj", name: "Sistema de bomba contra incendio EDJ", title: "Sistema EDJ para proyectos contra incendio en Chile", description: "Configuración que reúne una bomba eléctrica, una bomba diésel y una bomba jockey para revisar la continuidad de bombeo según el proyecto.", processRole: "Integra impulsión eléctrica, respaldo diésel y mantenimiento de presión en una misma conversación técnica.", driveType: "Eléctrico + diésel + jockey", contexts: ["Bodegas y centros de distribución", "Plantas industriales", "Infraestructura con requisitos de respaldo"], selectionInputs: ["Caudal y presión requeridos", "Disponibilidad eléctrica y diésel", "Plano de sala de bombas y fuente de agua", "Norma o requisito del proyecto"], verifiedSpecifications: [["Configuración", "Eléctrica + diésel + jockey"], ["Selección", "Se confirma para el proyecto"], ["Documentación", "Solicite la ficha aplicable"]], faq: [["¿Cuándo se revisa un sistema EDJ?", "Cuando el proyecto necesita analizar una combinación de accionamiento eléctrico, diésel y jockey."], ["¿Qué información se necesita?", "Caudal, presión, energía disponible, fuente de agua, plano y requisitos del proyecto."]], relatedSolutions: ["bombas-contra-incendio-bodegas", "bombas-contra-incendio-plantas-industriales", "bombas-contra-incendio-centros-datos"] },
  { slug: "bomba-diesel-contra-incendio", name: "Bomba diésel contra incendio", title: "Bomba diésel contra incendio para proyectos en Chile", description: "Alternativa para revisar cuando el proyecto requiere una fuente de accionamiento diésel o se ubica en un entorno con condiciones eléctricas a confirmar.", processRole: "Aporta una opción de accionamiento diésel dentro del análisis de la sala de bombas y del respaldo requerido.", driveType: "Diésel + jockey (según configuración)", contexts: ["Zonas remotas", "Petróleo, gas y logística de sitio", "Proyectos con respaldo a revisar"], selectionInputs: ["Condiciones ambientales y de instalación", "Disponibilidad y gestión de combustible", "Caudal, presión y fuente de agua", "Documentos del proyecto"], verifiedSpecifications: [["Accionamiento", "Diésel según configuración"], ["Mantenimiento", "Se define con la documentación del proyecto"], ["Parámetros", "Se confirma para el proyecto"]], faq: [["¿Qué se debe confirmar primero?", "El entorno, los requisitos de combustible, la fuente de agua y las condiciones de operación del proyecto."], ["¿Incluye certificaciones específicas?", "Solo se deben confirmar contra documentación verificable del modelo y alcance solicitado."]], relatedSolutions: ["bombas-contra-incendio-petroleo-gas", "bombas-contra-incendio-bodegas"] },
  { slug: "bomba-electrica-contra-incendio", name: "Bomba eléctrica contra incendio", title: "Bomba eléctrica contra incendio para proyectos en Chile", description: "Configuración para proyectos con alimentación eléctrica definida y necesidades de control que deben revisarse con la ingeniería del proyecto.", processRole: "Permite organizar la revisión de alimentación, control y requerimientos de bombeo antes de definir una configuración.", driveType: "Eléctrico + jockey (según configuración)", contexts: ["Plantas industriales", "Centros de datos", "Edificios e infraestructura con energía definida"], selectionInputs: ["Datos de alimentación eléctrica", "Caudal y presión", "Requisitos de control", "Plano y condiciones de instalación"], verifiedSpecifications: [["Accionamiento", "Eléctrico según configuración"], ["Control", "Se confirma para el proyecto"], ["Datos técnicos", "Solicite ficha aplicable"]], faq: [["¿Qué datos eléctricos se requieren?", "La información disponible de alimentación y los requisitos de control del proyecto."], ["¿Se puede definir sin caudal y presión?", "No; esos datos son necesarios para revisar la configuración."]], relatedSolutions: ["bombas-contra-incendio-plantas-industriales", "bombas-contra-incendio-centros-datos"] },
  { slug: "bomba-jockey-contra-incendio", name: "Bomba jockey para incendio", title: "Bomba jockey para sistemas contra incendio", description: "Elemento orientado a mantener la presión del sistema entre las condiciones definidas para el proyecto y la lógica de control aplicable.", processRole: "Ayuda a revisar el mantenimiento de presión y su relación con las bombas principales dentro del sistema.", driveType: "Jockey", contexts: ["Sistemas EDJ", "Configuraciones eléctricas", "Configuraciones diésel"], selectionInputs: ["Presión de mantenimiento", "Relación con la bomba principal", "Lógica de control", "Datos hidráulicos del sistema"], verifiedSpecifications: [["Función", "Mantenimiento de presión del sistema"], ["Ajustes", "Se confirman para el proyecto"], ["Integración", "Se revisa con la bomba principal"]], faq: [["¿La jockey reemplaza a la bomba principal?", "No; su función debe revisarse como parte de la estrategia de mantenimiento de presión."], ["¿Qué datos son necesarios?", "Presiones objetivo, información hidráulica y la configuración de las bombas principales."]], relatedSolutions: ["bombas-contra-incendio-bodegas", "bombas-contra-incendio-plantas-industriales"] },
  { slug: "bomba-incendio-eje-largo", name: "Bomba contra incendio de eje largo", title: "Bomba de eje largo contra incendio para toma de agua", description: "Alternativa para analizar cuando la fuente de agua, la toma o las condiciones de instalación requieren una configuración de eje largo.", processRole: "Centra la revisión en la fuente de agua, el arreglo de instalación y las condiciones físicas del sitio.", driveType: "Eléctrico o diésel según configuración", contexts: ["Tomas de agua", "Condiciones de nivel a revisar", "Sitios remotos"], selectionInputs: ["Datos de la fuente de agua", "Nivel, geometría y plano de instalación", "Caudal y presión", "Condiciones ambientales"], verifiedSpecifications: [["Aplicación", "Toma de agua según proyecto"], ["Accionamiento", "Se confirma para el proyecto"], ["Instalación", "Requiere datos de sitio"]], faq: [["¿Qué profundidad puede alcanzar?", "No se publica una cifra fija: depende de la toma, la configuración y las condiciones del proyecto."], ["¿Qué se debe enviar para revisión?", "Plano de instalación, información de la fuente de agua, caudal, presión y condiciones del sitio."]], relatedSolutions: ["bombas-contra-incendio-petroleo-gas"] },
];

const product = (item: Omit<ChileProduct, "selectionInputs" | "verifiedSpecifications" | "faq" | "relatedSolutions"> & Partial<Pick<ChileProduct, "selectionInputs" | "verifiedSpecifications" | "faq" | "relatedSolutions">>): ChileProduct => ({
  ...item,
  selectionInputs: item.selectionInputs ?? ["Caudal y presión requeridos", "Fuente de agua y condiciones de instalación", "Energía o accionamiento disponible", "Planos y requisitos del proyecto"],
  verifiedSpecifications: item.verifiedSpecifications ?? [["Familia de producto", item.name], ["Configuración", "Se confirma para el proyecto"], ["Documentación", "Solicite la ficha técnica aplicable"]],
  faq: item.faq ?? [["¿Qué información se necesita para cotizar?", "Comparta aplicación, caudal, presión, condiciones de instalación y los requisitos disponibles del proyecto."], ["¿Se publican parámetros definitivos?", "La configuración y los parámetros aplicables se confirman con la documentación del proyecto."]],
  relatedSolutions: item.relatedSolutions ?? [],
});

// Catálogo adaptado del sitemap público del sitio principal (26 productos, consultado el 2026-08-09).
// Los textos se localizan para Chile sin trasladar promesas de rendimiento, certificaciones o parámetros no confirmados.
export const chileProducts: ChileProduct[] = [
  product({ slug: "conjunto-electrico-jockey", sourceProductSlug: "2-electric-plus-jockey-pump-set", category: "Sistemas contra incendio", name: "Conjunto eléctrico + jockey", title: "Conjunto eléctrico y jockey para proyectos contra incendio en Chile", description: "Configuración de bomba principal eléctrica y bomba jockey para revisar la alimentación, el control y la presión de mantenimiento del proyecto.", processRole: "Integra una bomba eléctrica principal y una bomba jockey dentro de la revisión técnica del sistema.", driveType: "Eléctrico + jockey", contexts: ["Edificios e infraestructura", "Bodegas y centros de distribución", "Proyectos con alimentación eléctrica definida"], relatedSolutions: ["bombas-contra-incendio-bodegas", "bombas-contra-incendio-plantas-industriales"] }),
  product({ slug: "equipo-control-bdk", sourceProductSlug: "BDK-Accessories-set", category: "Control y accesorios", name: "Equipo de control automático BDK", title: "Equipo de control automático para bombas en Chile", description: "Equipo de control para revisar la lógica de operación y protección de una instalación de bombeo según su aplicación.", processRole: "Organiza la revisión de señales, automatización y condiciones de operación de las bombas.", driveType: "Control automático", contexts: ["Sistemas de agua", "Aplicaciones industriales", "Sistemas contra incendio"], selectionInputs: ["Diagrama de control disponible", "Tipo de bomba y motor", "Tensión y señales requeridas", "Secuencia de operación del proyecto"] }),
  product({ slug: "bomba-jockey-cdl", sourceProductSlug: "CDL-fire-pump-set", category: "Bombas contra incendio", name: "Bomba jockey CDL", title: "Bomba jockey CDL para sistemas de presión en Chile", description: "Bomba multietapa para analizar la mantención de presión y su integración con la bomba principal del sistema.", processRole: "Apoya la revisión de presión de mantenimiento en una configuración de bombeo.", driveType: "Eléctrico", contexts: ["Sistemas de presión", "Conjuntos contra incendio", "Aplicaciones de elevación de agua"], relatedSolutions: ["bombas-contra-incendio-bodegas", "bombas-contra-incendio-plantas-industriales"] }),
  product({ slug: "bomba-diesel-incendio", sourceProductSlug: "diesel-engine-fire-pump", category: "Sistemas contra incendio", name: "Bomba diésel contra incendio", title: "Bomba diésel contra incendio para proyectos en Chile", description: "Bomba accionada por motor diésel para revisar en proyectos donde se requiere analizar una fuente de accionamiento independiente.", processRole: "Permite evaluar el accionamiento diésel, la fuente de combustible y la configuración de bombeo.", driveType: "Diésel", contexts: ["Sitios remotos", "Instalaciones industriales", "Respaldo a revisar según proyecto"], relatedSolutions: ["bombas-contra-incendio-petroleo-gas", "bombas-contra-incendio-plantas-industriales"] }),
  product({ slug: "remolque-bomba-riego-diesel", sourceProductSlug: "diesel-engine-irrigation-pump-trailer-type", category: "Riego y bombeo móvil", name: "Remolque de bomba de riego diésel", title: "Remolque de bomba de riego diésel para proyectos en Chile", description: "Solución móvil para revisar necesidades temporales de riego, drenaje o transferencia de agua en terreno.", processRole: "Combina movilidad y accionamiento diésel para evaluar una operación de agua temporal o de terreno.", driveType: "Diésel móvil", contexts: ["Riego", "Drenaje temporal", "Transferencia de agua en faena"], selectionInputs: ["Caudal y altura requeridos", "Origen y destino del agua", "Condiciones de traslado", "Acceso y condiciones del terreno"] }),
  product({ slug: "bomba-incendio-eje-largo-diesel", sourceProductSlug: "diesel-engine-long-shaft-fire-pump", category: "Bombas contra incendio", name: "Bomba contra incendio de eje largo diésel", title: "Bomba de eje largo diésel para toma de agua en Chile", description: "Configuración de eje largo y accionamiento diésel para estudiar fuentes de agua y condiciones de instalación específicas.", processRole: "Centra la selección en toma de agua, disposición física y accionamiento diésel.", driveType: "Diésel + eje largo", contexts: ["Toma de agua", "Sitios remotos", "Infraestructura industrial"], relatedSolutions: ["bombas-contra-incendio-petroleo-gas"] }),
  product({ slug: "conjunto-diesel-jockey", sourceProductSlug: "diesel-engine-plus-jockey-pump-set", category: "Sistemas contra incendio", name: "Conjunto diésel + jockey", title: "Conjunto diésel y jockey para proyectos contra incendio en Chile", description: "Configuración de bomba principal diésel y bomba jockey para revisar respaldo, presión de mantenimiento y condiciones de combustible.", processRole: "Relaciona la bomba diésel principal con la presión de mantenimiento del conjunto.", driveType: "Diésel + jockey", contexts: ["Bodegas", "Plantas industriales", "Zonas con suministro eléctrico a revisar"], relatedSolutions: ["bombas-contra-incendio-petroleo-gas", "bombas-contra-incendio-bodegas"] }),
  product({ slug: "sistema-incendio-edj", sourceProductSlug: "edj-fire-pump-set", category: "Sistemas contra incendio", name: "Sistema contra incendio EDJ", title: "Sistema EDJ para proyectos contra incendio en Chile", description: "Configuración que reúne bomba eléctrica, bomba diésel y bomba jockey para revisar continuidad y control de presión según proyecto.", processRole: "Integra accionamiento eléctrico, respaldo diésel y mantención de presión en una misma revisión.", driveType: "Eléctrico + diésel + jockey", contexts: ["Bodegas y logística", "Plantas industriales", "Infraestructura crítica"], relatedSolutions: ["bombas-contra-incendio-bodegas", "bombas-contra-incendio-centros-datos", "bombas-contra-incendio-plantas-industriales"] }),
  product({ slug: "sistema-incendio-ej", sourceProductSlug: "ej-fire-pump-set", category: "Sistemas contra incendio", name: "Sistema contra incendio EJ", title: "Sistema EJ eléctrico y jockey para Chile", description: "Configuración de bomba principal eléctrica y jockey para organizar los requisitos de alimentación, control y presión del proyecto.", processRole: "Revisa la relación entre bombeo eléctrico principal y presión de mantenimiento.", driveType: "Eléctrico + jockey", contexts: ["Edificios", "Bodegas", "Plantas industriales"], relatedSolutions: ["bombas-contra-incendio-bodegas", "bombas-contra-incendio-plantas-industriales"] }),
  product({ slug: "bomba-incendio-carcasa-partida-electrica", sourceProductSlug: "electric-horizontal-split-end-suction-pump", category: "Bombas contra incendio", name: "Bomba contra incendio de carcasa partida eléctrica", title: "Bomba de carcasa partida eléctrica para Chile", description: "Bomba eléctrica de carcasa partida para revisar como parte de una configuración contra incendio con condiciones hidráulicas definidas.", processRole: "Aporta una alternativa de bomba principal eléctrica para estudiar con los datos hidráulicos del proyecto.", driveType: "Eléctrico", contexts: ["Redes contra incendio", "Instalaciones industriales", "Proyectos con sala de bombas"], relatedSolutions: ["bombas-contra-incendio-plantas-industriales"] }),
  product({ slug: "bomba-incendio-eje-largo-electrica", sourceProductSlug: "electric-long-shaft-fire-pump", category: "Bombas contra incendio", name: "Bomba contra incendio de eje largo eléctrica", title: "Bomba de eje largo eléctrica para toma de agua en Chile", description: "Configuración eléctrica de eje largo para analizar proyectos con toma de agua y requisitos de instalación vertical.", processRole: "Vincula la fuente de agua y la instalación vertical con la alimentación eléctrica del proyecto.", driveType: "Eléctrico + eje largo", contexts: ["Tomas de agua", "Infraestructura industrial", "Instalaciones verticales"], relatedSolutions: ["bombas-contra-incendio-petroleo-gas"] }),
  product({ slug: "equipo-abastecimiento-agua-variador-frecuencia", sourceProductSlug: "frequency-conversion-water-supply-equipment", category: "Abastecimiento de agua", name: "Equipo de abastecimiento de agua con variador de frecuencia", title: "Equipo de agua con variador de frecuencia para Chile", description: "Equipo para revisar la gestión de presión y abastecimiento de agua en aplicaciones de edificios o servicios.", processRole: "Permite estructurar una consulta sobre presión, demanda y control de abastecimiento de agua.", driveType: "Eléctrico con variador", contexts: ["Edificios", "Servicios", "Abastecimiento de agua"], selectionInputs: ["Demanda de agua", "Presión requerida", "Origen de agua", "Datos eléctricos y de control"] }),
  product({ slug: "grupo-bomba-presion-horizontal", sourceProductSlug: "horizontal-booster-pump-group", category: "Abastecimiento de agua", name: "Grupo de bombas de presión horizontal", title: "Grupo de presión horizontal para proyectos en Chile", description: "Grupo de bombeo horizontal para estudiar requerimientos de presurización y abastecimiento de agua.", processRole: "Organiza la revisión de bombas, presión, demanda y condiciones de instalación.", driveType: "Eléctrico", contexts: ["Edificios", "Sistemas de agua", "Aplicaciones de presión"], selectionInputs: ["Demanda máxima", "Presión de servicio", "Espacio de instalación", "Datos de red y alimentación"] }),
  product({ slug: "estacion-bombeo-prefabricada-frp", sourceProductSlug: "integrated-prefabricated-pump-station-frp", category: "Aguas servidas y drenaje", name: "Estación de bombeo prefabricada FRP", title: "Estación de bombeo prefabricada FRP para Chile", description: "Estación prefabricada para revisar recolección, elevación o drenaje de agua de lluvia y aguas servidas según el sitio.", processRole: "Reúne la revisión de caudal, pozo, conducción y condiciones de instalación enterrada o de terreno.", driveType: "Sistema prefabricado", contexts: ["Drenaje urbano", "Aguas lluvias", "Elevación de aguas servidas"], selectionInputs: ["Caudal de entrada", "Profundidad y geometría", "Condiciones del terreno", "Conexiones de entrada y descarga"] }),
  product({ slug: "bomba-centrifuga-vertical-isg", sourceProductSlug: "ISG-Water-Supply-Series-pump", category: "Bombas para agua", name: "Bomba centrífuga vertical ISG", title: "Bomba centrífuga vertical ISG para agua en Chile", description: "Bomba centrífuga vertical de una etapa para revisar transferencia o presurización de agua en instalaciones compactas.", processRole: "Permite analizar una disposición vertical para requisitos de agua del proyecto.", driveType: "Eléctrico", contexts: ["Transferencia de agua", "Edificios", "Sistemas de presión"] }),
  product({ slug: "bomba-centrifuga-horizontal-isw", sourceProductSlug: "ISW-Water-Supply-Series-pump", category: "Bombas para agua", name: "Bomba centrífuga horizontal ISW", title: "Bomba centrífuga horizontal ISW para agua en Chile", description: "Bomba centrífuga horizontal de una etapa para revisar transferencia de agua y disposición de equipos.", processRole: "Apoya la evaluación de caudal, altura y espacio de instalación de una bomba horizontal.", driveType: "Eléctrico", contexts: ["Transferencia de agua", "Aplicaciones industriales", "Servicios de edificio"] }),
  product({ slug: "bomba-sumergible-aguas-servidas", sourceProductSlug: "submersible-sewage-pump", category: "Aguas servidas y drenaje", name: "Bomba sumergible para aguas servidas", title: "Bomba sumergible para aguas servidas en Chile", description: "Bomba sumergible para revisar conducción de aguas servidas o efluentes conforme a las condiciones del líquido y del pozo.", processRole: "Relaciona el tipo de efluente, sólidos, altura y disposición del pozo con la selección.", driveType: "Eléctrico sumergible", contexts: ["Aguas servidas", "Pozos", "Drenaje de instalaciones"], selectionInputs: ["Tipo de líquido y sólidos", "Caudal y altura", "Geometría del pozo", "Alimentación y control"] }),
  product({ slug: "grupo-presion-vertical", sourceProductSlug: "Vertical-booster-pump-group", category: "Abastecimiento de agua", name: "Grupo de presión vertical", title: "Grupo de presión vertical para proyectos en Chile", description: "Grupo de bombas verticales para analizar necesidades de presión y abastecimiento de agua en el proyecto.", processRole: "Organiza la revisión de demanda, presión, control y espacio de una configuración vertical.", driveType: "Eléctrico", contexts: ["Edificios", "Abastecimiento de agua", "Presurización"] }),
  product({ slug: "bomba-multietapa-jockey-acero-inoxidable", sourceProductSlug: "vertical-stainless-steel-multistage-pump-jockey-pump", category: "Bombas contra incendio", name: "Bomba jockey multietapa de acero inoxidable", title: "Bomba jockey multietapa de acero inoxidable para Chile", description: "Bomba multietapa vertical para revisar mantención de presión o aplicaciones de elevación según el sistema.", processRole: "Permite estudiar el papel de una bomba multietapa como jockey o bomba de presión.", driveType: "Eléctrico", contexts: ["Sistemas contra incendio", "Presurización", "Elevación de agua"], relatedSolutions: ["bombas-contra-incendio-bodegas", "bombas-contra-incendio-plantas-industriales"] }),
  product({ slug: "bomba-sumergible-corte-wqk", sourceProductSlug: "WQK-Sewage-Pump-Series-Pump", category: "Aguas servidas y drenaje", name: "Bomba sumergible de corte WQK", title: "Bomba sumergible de corte WQK para aguas servidas", description: "Bomba sumergible con sistema de corte para revisar efluentes con materiales fibrosos o sólidos, según las condiciones de aplicación.", processRole: "Ayuda a evaluar el tipo de efluente, presencia de sólidos y condiciones de pozo.", driveType: "Eléctrico sumergible", contexts: ["Aguas servidas con sólidos", "Pozos de bombeo", "Instalaciones de drenaje"] }),
  product({ slug: "bomba-sumergible-acero-inoxidable-wqp", sourceProductSlug: "WQP-Sewage-Pump-Series-Pump", category: "Aguas servidas y drenaje", name: "Bomba sumergible de acero inoxidable WQP", title: "Bomba sumergible de acero inoxidable WQP para Chile", description: "Bomba sumergible de acero inoxidable para revisar aplicaciones de aguas servidas con condiciones de material a confirmar.", processRole: "Permite estudiar el medio bombeado y los requisitos de material de una instalación sumergible.", driveType: "Eléctrico sumergible", contexts: ["Aguas servidas", "Aplicaciones con requisitos de material", "Drenaje"] }),
  product({ slug: "bomba-incendio-multietapa-vertical-xbd-dl", sourceProductSlug: "XBD-DL-fire-pump-set", category: "Bombas contra incendio", name: "Bomba contra incendio multietapa vertical XBD-DL", title: "Bomba contra incendio multietapa vertical XBD-DL en Chile", description: "Bomba vertical multietapa para revisar necesidades de presión en una configuración contra incendio.", processRole: "Aporta una alternativa vertical multietapa para estudiar junto con los requisitos hidráulicos del proyecto.", driveType: "Eléctrico", contexts: ["Sistemas contra incendio", "Instalaciones compactas", "Aplicaciones de presión"] }),
  product({ slug: "bomba-incendio-vertical-etapa-unica-xbd-l", sourceProductSlug: "XBD-L-fire-pump-set", category: "Bombas contra incendio", name: "Bomba contra incendio vertical de etapa única XBD-L", title: "Bomba contra incendio vertical XBD-L en Chile", description: "Bomba vertical de etapa única para revisar como parte de un sistema de suministro de agua contra incendio.", processRole: "Permite evaluar una disposición vertical con los datos hidráulicos y condiciones de instalación disponibles.", driveType: "Eléctrico", contexts: ["Sistemas contra incendio", "Edificios", "Instalaciones de presión"] }),
  product({ slug: "bomba-sumergible-yw", sourceProductSlug: "YW-Sewage-Pump-Series-Pump", category: "Aguas servidas y drenaje", name: "Bomba sumergible YW", title: "Bomba sumergible YW para aguas servidas en Chile", description: "Bomba sumergible para revisar evacuación de aguas servidas y condiciones de instalación en pozo.", processRole: "Relaciona las condiciones del efluente y del pozo con una selección de bomba sumergible.", driveType: "Eléctrico sumergible", contexts: ["Aguas servidas", "Drenaje", "Pozos de bombeo"] }),
  product({ slug: "bomba-autocebante-acoplamiento-directo-zwl-zxl", sourceProductSlug: "ZWL-ZXL-Water-Supply-Series-pump", category: "Bombas para agua", name: "Bomba autocebante de acoplamiento directo ZWL/ZXL", title: "Bomba autocebante ZWL/ZXL para proyectos en Chile", description: "Bomba centrífuga autocebante de diseño compacto para analizar transferencia de agua y condiciones de succión.", processRole: "Centra la consulta en la succión, el líquido, el caudal y la disposición de instalación.", driveType: "Eléctrico", contexts: ["Transferencia de agua", "Drenaje", "Aplicaciones de autocebado"] }),
  product({ slug: "bomba-autocebante-zw-zx", sourceProductSlug: "ZWZX-Water-Supply-Series-pump", category: "Bombas para agua", name: "Bomba autocebante ZW/ZX", title: "Bomba autocebante ZW/ZX para proyectos en Chile", description: "Bomba centrífuga autocebante para estudiar transferencia de agua con conjunto de bomba y motor a revisar según la instalación.", processRole: "Ayuda a ordenar los datos de succión, caudal, líquido y disposición de equipos.", driveType: "Eléctrico", contexts: ["Transferencia de agua", "Drenaje", "Aplicaciones de autocebado"] }),
];

export const legacyProductRedirects: Record<string, string> = {
  "sistema-bomba-incendio-edj": "sistema-incendio-edj",
  "bomba-diesel-contra-incendio": "bomba-diesel-incendio",
  "bomba-electrica-contra-incendio": "conjunto-electrico-jockey",
  "bomba-jockey-contra-incendio": "bomba-jockey-cdl",
  "bomba-incendio-eje-largo": "bomba-incendio-eje-largo-electrica",
};

export type ChileSolution = { slug: string; name: string; title: string; intro: string; challenge: string; deployment: string; inputs: string[]; products: string[]; faq: [string, string][] };
export const chileSolutions: ChileSolution[] = [
  { slug: "bombas-contra-incendio-bodegas", name: "Bodegas y logística", title: "Bombas contra incendio para bodegas y logística", intro: "Guía para preparar una conversación técnica sobre sistemas de bombeo en bodegas, centros de distribución y operaciones logísticas en Chile.", challenge: "La revisión suele involucrar continuidad de operación, distribución del edificio, fuente de agua y documentación del proyecto.", deployment: "Se revisan las configuraciones de bombeo, la sala de bombas, el accionamiento disponible y los requisitos del proyecto antes de proponer una alternativa.", inputs: ["Plano o esquema de instalación", "Caudal y presión requeridos", "Fuente de agua", "Etapa de expansión o cambios previstos"], products: ["sistema-incendio-edj", "bomba-jockey-cdl", "conjunto-electrico-jockey"], faq: [["¿Qué conviene preparar?", "Los planos disponibles, caudal, presión, fuente de agua y los documentos del proyecto."]] },
  { slug: "bombas-contra-incendio-plantas-industriales", name: "Plantas industriales", title: "Bombas contra incendio para plantas industriales", intro: "Contenido de apoyo para proyectos industriales que necesitan ordenar variables de bombeo, condiciones de instalación y documentación técnica.", challenge: "Las condiciones de proceso, el entorno y la continuidad de la planta requieren que la selección se base en información del sitio.", deployment: "La revisión conecta necesidades hidráulicas, accionamiento, sala de bombas y documentación de proyecto sin asumir condiciones no verificadas.", inputs: ["Uso y entorno de instalación", "Caudal y presión", "Alimentación disponible", "Planos y requisitos técnicos"], products: ["sistema-incendio-edj", "bomba-incendio-carcasa-partida-electrica", "bomba-jockey-cdl", "bomba-diesel-incendio"], faq: [["¿Se publican parámetros fijos?", "Los valores deben confirmarse con los documentos y condiciones de cada proyecto."]] },
  { slug: "bombas-contra-incendio-centros-datos", name: "Centros de datos", title: "Bombas contra incendio para centros de datos", intro: "Punto de partida para proyectos de infraestructura crítica que necesitan coordinar documentación, accionamiento y variables de selección.", challenge: "La coordinación de ingeniería, la información disponible y los requisitos del proyecto deben revisarse antes de definir un sistema.", deployment: "Se organiza la conversación sobre alimentación, respaldo a evaluar, controles, fuente de agua y documentación técnica.", inputs: ["Requisitos de ingeniería", "Datos eléctricos disponibles", "Caudal, presión y fuente de agua", "Planos y coordinación de sala"], products: ["sistema-incendio-edj", "conjunto-electrico-jockey", "bomba-incendio-carcasa-partida-electrica"], faq: [["¿Se garantiza disponibilidad?", "No se hacen promesas de disponibilidad: se revisan los requisitos documentados del proyecto."]] },
  { slug: "bombas-contra-incendio-petroleo-gas", name: "Petróleo, gas y zonas remotas", title: "Bombas contra incendio para petróleo, gas y zonas remotas", intro: "Guía para recopilar información de proyectos con condiciones remotas, ambientales o logísticas que requieren una revisión técnica específica.", challenge: "Las condiciones ambientales, la logística y la energía disponible pueden modificar la configuración a estudiar.", deployment: "Se revisan accionamiento, fuente de agua, combustibles, disposición de sitio y documentación de proyecto sin declarar certificaciones no verificadas.", inputs: ["Ubicación y condiciones ambientales", "Fuente de agua", "Datos de energía y combustible", "Planos, logística y requisitos documentados"], products: ["bomba-diesel-incendio", "bomba-incendio-eje-largo-diesel", "bomba-incendio-eje-largo-electrica"], faq: [["¿La solución incluye certificación especial?", "Solo se puede confirmar una certificación concreta con documentación válida del producto y proyecto."]] },
];

export const trustPages: Record<string, { title: string; eyebrow: string; intro: string; sections: [string, string][] }> = {
  empresa: { eyebrow: "EMPRESA", title: "GRIMM PUMP para proyectos en Chile", intro: "GRIMM PUMP es la marca de exportación de Grimm Water Treatment (Zhejiang) Co., Ltd. para compradores que necesitan una conversación técnica clara sobre sistemas de bombeo contra incendio.", sections: [["Alcance", "Atendemos consultas para proyectos en Chile y otros mercados de Latinoamérica desde una operación de exportación; esta página no declara una oficina local chilena."], ["Cómo trabajamos", "La configuración se revisa con caudal, presión, fuente de agua, accionamiento, planos y documentos disponibles."], ["Contacto", "Use los canales de contacto publicados para compartir la información de proyecto."]] },
  fabrica: { eyebrow: "INFORMACIÓN DE FABRICACIÓN", title: "Documentación de fabricación según proyecto", intro: "La información de fabricación y las imágenes deben corresponder a material verificable. Para un proyecto concreto, solicite la documentación disponible.", sections: [["Material verificable", "No se publican imágenes de fábrica ni cifras de capacidad sin una fuente interna que pueda verificarse."], ["Solicitud de información", "Indique el sistema y la aplicación para revisar qué documentación puede compartirse."]] },
  pruebas: { eyebrow: "PRUEBAS", title: "Información de pruebas con alcance verificable", intro: "La evidencia de pruebas debe revisarse contra el modelo, la configuración y el alcance real del proyecto.", sections: [["Alcance", "No se publican resultados, videos ni indicadores sin documentación verificable."], ["Siguiente paso", "Comparta el producto y los requisitos del proyecto para solicitar la información aplicable."]] },
  certificados: { eyebrow: "CERTIFICADOS", title: "Certificados y documentación verificable", intro: "Solo deben compartirse certificados con alcance, vigencia y relación de producto comprobables.", sections: [["Criterio de publicación", "No se listan normas, certificados ni aprobaciones sin documentos que permitan verificar su aplicabilidad."], ["Solicitud", "Solicite documentación indicando el producto, el mercado y el requisito del proyecto."]] },
  proyectos: { eyebrow: "PROYECTOS", title: "Información de proyectos con autorización", intro: "Los proyectos solo se publican cuando existe autorización y datos verificables para hacerlo.", sections: [["Privacidad y evidencia", "No inventamos casos, clientes, ubicaciones ni resultados de proyectos."], ["Consulta", "Para revisar experiencia relevante, comparta el tipo de instalación y los requisitos del proyecto."]] },
  descargas: { eyebrow: "DESCARGAS", title: "Solicite documentación técnica", intro: "Los catálogos, fichas y documentos de selección deben corresponder al producto y a la versión aplicable.", sections: [["Documentos", "Solicite catálogo, datos técnicos o información de configuración indicando el sistema requerido."], ["Control de versión", "Los documentos publicados o compartidos deben incluir producto, idioma, versión y fecha cuando estén disponibles."]] },
  guias: { eyebrow: "GUÍAS", title: "Guías para preparar una consulta técnica", intro: "Material de apoyo para ordenar la información que un equipo de ingeniería o compras puede preparar antes de solicitar una revisión.", sections: [["Información de selección", "Caudal, presión, fuente de agua, accionamiento, planos, condiciones de instalación y requisitos del proyecto."], ["Uso responsable", "La guía no sustituye la ingeniería, las normas aplicables ni la validación específica de un proyecto."]] },
  contacto: { eyebrow: "CONTACTO", title: "Cuéntenos sobre su proyecto", intro: "Comparta la información disponible de su proyecto en Chile para iniciar una revisión de configuración y documentación.", sections: [] },
  "politica-de-privacidad": { eyebrow: "PRIVACIDAD", title: "Política de privacidad", intro: "Esta página explica el uso de los datos enviados mediante el formulario de consulta.", sections: [["Datos recogidos", "El formulario recoge datos de contacto y de proyecto necesarios para responder la solicitud."], ["Uso", "Los datos se usan para atender la consulta y no se incluyen en la URL pública."], ["Contacto", "Puede utilizar los canales de contacto del sitio para consultas sobre sus datos."]] },
};
