import { createHash, randomUUID } from "node:crypto";
import { getDatabase } from "@/lib/database";

type Row = Record<string, unknown>;
type NewsSite = { siteId: string; enabled: boolean; brandName: string; siteUrl: string; industry: string; industryScope: string; locale: string; publicationLanguage: string; timezone: string; listRoute: string; detailRoutePattern: string; rssRoute: string; sitemapRoute: string; candidateMaxAgeHours: number; fallbackCandidateMaxAgeDays: number; minScore: number; maxInternalProductLinks: number; defaultAuthorType: string; requireFrontendVerification: boolean };
type NewsSource = { id: string; siteId: string; tier: "primary" | "fallback"; domain: string; sourceType: string; allowedTopics: string[]; allowedLanguages: string[]; feedUrl: string; sourceTrustScore: number };
type Candidate = { id: string; siteId: string; title: string; summary: string; sourceName: string; sourceUrl: string; sourcePublishedAt: string; sourceAuthor: string | null; language: string | null; relevanceScore: number; contentFingerprint: string };
const iso = () => new Date().toISOString();
const asString = (value: unknown) => value == null ? "" : String(value);
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
const json = <T>(value: unknown, fallback: T) => { try { return JSON.parse(asString(value)) as T; } catch { return fallback; } };
const safeText = (value: string) => value.replace(/<!\[CDATA\[|\]\]>/g, "").replace(/<[^>]*>/g, " ").replace(/&nbsp;/gi, " ").replace(/&amp;/gi, "&").replace(/&quot;/gi, '"').replace(/&#39;/g, "'").replace(/\s+/g, " ").trim();

function rowToSite(row: Row): NewsSite { return { siteId: asString(row.site_id), enabled: Number(row.enabled) === 1, brandName: asString(row.brand_name), siteUrl: asString(row.site_url).replace(/\/$/, ""), industry: asString(row.industry), industryScope: asString(row.industry_scope), locale: asString(row.locale), publicationLanguage: asString(row.publication_language), timezone: asString(row.timezone), listRoute: asString(row.list_route), detailRoutePattern: asString(row.detail_route_pattern), rssRoute: asString(row.rss_route), sitemapRoute: asString(row.sitemap_route), candidateMaxAgeHours: Number(row.candidate_max_age_hours), fallbackCandidateMaxAgeDays: Number(row.fallback_candidate_max_age_days), minScore: Number(row.min_score), maxInternalProductLinks: Number(row.max_internal_product_links), defaultAuthorType: asString(row.default_author_type), requireFrontendVerification: Number(row.require_frontend_verification) === 1 }; }
function rowToSource(row: Row): NewsSource { return { id: asString(row.id), siteId: asString(row.site_id), tier: asString(row.tier) === "fallback" ? "fallback" : "primary", domain: asString(row.domain), sourceType: asString(row.source_type), allowedTopics: json(row.allowed_topics, []), allowedLanguages: json(row.allowed_languages, []), feedUrl: asString(row.feed_url), sourceTrustScore: Number(row.source_trust_score) }; }
function normalizeUrl(value: string) { const url = new URL(value); ["utm_source", "utm_medium", "utm_campaign", "utm_term", "utm_content", "fbclid", "gclid"].forEach((key) => url.searchParams.delete(key)); url.hash = ""; return url.toString(); }
function sourceName(domain: string) { return domain.replace(/^www\./, ""); }
function cycleKey(hours: number, date = new Date()) { return `${hours}h-${Math.floor(date.getTime() / (hours * 60 * 60 * 1000))}`; }
function validSourceUrl(source: NewsSource) { try { const url = new URL(source.feedUrl); return url.protocol === "https:" && url.hostname === source.domain; } catch { return false; } }
function itemPart(item: string, tag: string) { const match = item.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`, "i")); return match ? safeText(match[1]) : ""; }
function parseRss(xml: string) { return [...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/gi)].map((match) => { const item = match[1]; return { title: itemPart(item, "title"), link: itemPart(item, "link"), description: itemPart(item, "description"), author: itemPart(item, "dc:creator") || itemPart(item, "author"), publishedAt: itemPart(item, "pubDate") || itemPart(item, "dc:date"), category: [...item.matchAll(/<category(?:\s[^>]*)?>([\s\S]*?)<\/category>/gi)].map((category) => safeText(category[1])) }; }).filter((item) => item.title && item.link && item.publishedAt); }
function scoreCandidate(site: NewsSite, source: NewsSource, item: { title: string; description: string; category: string[]; publishedAt: string }) { const ageHours = (Date.now() - Date.parse(item.publishedAt)) / 3600000; const terms = `${site.industryScope} ${source.allowedTopics.join(" ")} incendio protección seguridad bomberos fire`.toLocaleLowerCase(site.locale); const text = `${item.title} ${item.description} ${item.category.join(" ")}`.toLocaleLowerCase(site.locale); const matches = terms.split(/[^\p{L}\p{N}]+/u).filter((word) => word.length > 4).filter((word) => text.includes(word)).length; const relevance = Math.min(30, matches * 6); const freshness = ageHours <= 24 ? 25 : ageHours <= site.candidateMaxAgeHours ? 18 : ageHours <= site.fallbackCandidateMaxAgeDays * 24 ? 8 : 0; const sourceQuality = Math.round(source.sourceTrustScore * .15); const language = source.allowedLanguages.includes("es") ? 15 : 8; const impact = /incend|segurid|protecci|emergenc|bombero|normativ|prevenci/i.test(text) ? 15 : 0; return { score: relevance + freshness + sourceQuality + language + impact, ageHours, relevance }; }
function slugFrom(title: string, fingerprint: string) { const clean = title.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 120); return `${clean || "noticia"}-${fingerprint.slice(0, 10)}`; }
async function audit(siteId: string, eventType: string, entityType: string, entityId: string | undefined, result: "success" | "failure", details: Record<string, unknown>) { const db = await getDatabase(); await db.execute({ sql: "INSERT INTO industry_news_audit_events (id,site_id,event_type,entity_type,entity_id,details,result,created_at) VALUES (?,?,?,?,?,?,?,?)", args: [randomUUID(), siteId, eventType, entityType, entityId || null, JSON.stringify(details), result, iso()] }); }
async function acquireLock(siteId: string, type: string, ttlMinutes = 20) { const db = await getDatabase(); const key = `news:${type}:${siteId}`; const now = iso(); const expires = new Date(Date.now() + ttlMinutes * 60000).toISOString(); const result = await db.execute({ sql: "INSERT INTO industry_news_locks (lock_key,site_id,expires_at,heartbeat_at,created_at) VALUES (?,?,?,?,?) ON CONFLICT (lock_key) DO UPDATE SET expires_at=EXCLUDED.expires_at,heartbeat_at=EXCLUDED.heartbeat_at WHERE industry_news_locks.expires_at < ? RETURNING lock_key", args: [key, siteId, expires, now, now, now] }); return result.rows.length ? key : null; }
async function releaseLock(key: string | null) { if (!key) return; const db = await getDatabase(); await db.execute({ sql: "DELETE FROM industry_news_locks WHERE lock_key=?", args: [key] }); }

export async function getNewsSites() { const db = await getDatabase(); const result = await db.execute("SELECT * FROM industry_news_sites WHERE enabled=1 ORDER BY site_id"); return result.rows.map(rowToSite); }
export async function getDefaultNewsSite() { return (await getNewsSites())[0] || null; }
export async function getPublicNews(siteId: string) { const db = await getDatabase(); const result = await db.execute({ sql: "SELECT * FROM industry_news_articles WHERE site_id=? AND status='published' AND published_at IS NOT NULL AND archived_at IS NULL ORDER BY published_at DESC", args: [siteId] }); return result.rows; }
export async function getPublicNewsArticle(siteId: string, slug: string) { const db = await getDatabase(); const result = await db.execute({ sql: "SELECT * FROM industry_news_articles WHERE site_id=? AND slug=? AND status='published' AND published_at IS NOT NULL AND archived_at IS NULL LIMIT 1", args: [siteId, slug] }); return result.rows[0] || null; }

export async function ingestNewsSite(site: NewsSite) {
  const db = await getDatabase(); const key = await acquireLock(site.siteId, "ingest"); if (!key) return { siteId: site.siteId, status: "locked" };
  const runKey = cycleKey(12); const now = iso();
  try {
    const previous = await db.execute({ sql: "SELECT status FROM industry_news_ingest_runs WHERE site_id=? AND cycle_key=?", args: [site.siteId, runKey] });
    if (previous.rows[0]?.status === "success") return { siteId: site.siteId, status: "already_completed", cycleKey: runKey };
    const runId = randomUUID(); await db.execute({ sql: "INSERT INTO industry_news_ingest_runs (id,site_id,cycle_key,status,started_at,created_at) VALUES (?,?,?,?,?,?) ON CONFLICT (site_id,cycle_key) DO UPDATE SET status='running',started_at=EXCLUDED.started_at,error_summary=NULL", args: [runId, site.siteId, runKey, "running", now, now] });
    const sources = (await db.execute({ sql: "SELECT * FROM industry_news_sources WHERE site_id=? AND is_enabled=1 ORDER BY CASE tier WHEN 'primary' THEN 0 ELSE 1 END, source_trust_score DESC", args: [site.siteId] })).rows.map(rowToSource);
    let discovered = 0, candidates = 0, rejected = 0; const errors: string[] = [];
    for (const source of sources) {
      if (!validSourceUrl(source)) { errors.push(`${source.id}:invalid_source_url`); continue; }
      try {
        const response = await fetch(source.feedUrl, { headers: { "user-agent": "GRIMMPUMPNewsBot/1.0 (+https://grimmfirepump.cl/es/noticias)" }, signal: AbortSignal.timeout(15000), cache: "no-store" });
        if (!response.ok) throw new Error(`source_http_${response.status}`);
        const items = parseRss(await response.text());
        await db.execute({ sql: "UPDATE industry_news_sources SET last_healthy_at=?,updated_at=? WHERE id=?", args: [now, now, source.id] });
        for (const item of items) {
          discovered++; let normalized: string; let sourceDate: Date;
          try { normalized = normalizeUrl(item.link); sourceDate = new Date(item.publishedAt); if (Number.isNaN(sourceDate.valueOf())) throw new Error("invalid_date"); } catch { rejected++; continue; }
          const scored = scoreCandidate(site, source, item); const fingerprint = hash(`${normalized}\u0000${item.title}\u0000${item.description}`); const urlHash = hash(normalized); const titleHash = hash(item.title.toLocaleLowerCase(site.locale));
          const accepted = scored.ageHours >= -6 && scored.ageHours <= site.fallbackCandidateMaxAgeDays * 24 && scored.relevance > 0 && scored.score >= site.minScore;
          const status = accepted ? "candidate" : "rejected"; if (accepted) candidates++; else rejected++;
          await db.execute({ sql: "INSERT INTO industry_news_candidates (id,site_id,source_id,normalized_url,normalized_url_hash,title,title_hash,summary,source_name,source_published_at,source_author,language,media_url,image_rights_status,industry_tags,relevance_score,status,reject_reason,content_fingerprint,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT (site_id,normalized_url_hash) DO NOTHING", args: [randomUUID(), site.siteId, source.id, normalized, urlHash, item.title, titleHash, item.description.slice(0, 1800) || null, sourceName(source.domain), sourceDate.toISOString(), item.author || null, source.allowedLanguages[0] || null, null, "no_external_image_used", JSON.stringify(item.category), scored.score, status, accepted ? null : "age_scope_or_score_gate", fingerprint, now, now] });
        }
      } catch (error) { errors.push(`${source.id}:${error instanceof Error ? error.message : "source_failure"}`); }
    }
    await db.execute({ sql: "UPDATE industry_news_ingest_runs SET status=?,finished_at=?,discovered_count=?,candidate_count=?,rejected_count=?,error_summary=? WHERE site_id=? AND cycle_key=?", args: [errors.length ? "partial_success" : "success", iso(), discovered, candidates, rejected, errors.length ? JSON.stringify(errors) : null, site.siteId, runKey] });
    await audit(site.siteId, "news_ingest_completed", "ingest_run", runKey, errors.length ? "failure" : "success", { discovered, candidates, rejected, errors });
    return { siteId: site.siteId, status: errors.length ? "partial_success" : "success", discovered, candidates, rejected, errors, cycleKey: runKey };
  } catch (error) { await audit(site.siteId, "news_ingest_failed", "ingest_run", runKey, "failure", { error: error instanceof Error ? error.message : "unknown" }); throw error; } finally { await releaseLock(key); }
}

function composeSpanish(candidate: Candidate, theme: Row | undefined) {
  const factual = candidate.summary || "La fuente no proporcionó un resumen suficiente para ampliar los hechos sin reproducir el contenido original.";
  const product = theme ? `\n\n## Contexto de proyecto\n\nPara los responsables de instalaciones, esta actualización puede incorporarse a la revisión documental y operativa del proyecto. Cuando corresponda al alcance técnico, consulte el sistema relacionado: [${asString(theme.product_name)}](${asString(theme.product_url)}). La configuración final se confirma según caudal, presión, suministro de agua, accionamiento y requisitos del proyecto.` : "";
  return `## Hechos comunicados por la fuente\n\n${factual}\n\nLa información anterior se atribuye a ${candidate.sourceName}. Esta página resume el anuncio y no sustituye el documento original, sus actualizaciones ni las instrucciones de la autoridad o entidad emisora.\n\n## Por qué puede ser relevante\n\nLas novedades relacionadas con prevención, respuesta o seguridad contra incendios pueden afectar la coordinación de instalaciones, la preparación de información técnica y la revisión de condiciones operativas. La relevancia concreta depende del tipo de instalación, la normativa aplicable y el alcance de cada proyecto.\n\n## Puntos de revisión para equipos de proyecto\n\n- Confirmar el alcance y la fecha de vigencia directamente con la fuente original.\n- Revisar si la novedad modifica información de riesgo, operación, mantenimiento o coordinación del proyecto.\n- Mantener separadas las decisiones de ingeniería de cualquier interpretación editorial de esta nota.${product}\n\n## Fuente original\n\n- Fuente: ${candidate.sourceName}\n- Publicación original: ${new Intl.DateTimeFormat("es-CL", { dateStyle: "long", timeZone: "America/Santiago" }).format(new Date(candidate.sourcePublishedAt))}\n- Enlace: ${candidate.sourceUrl}\n\n## Nota editorial\n\nEsta es una síntesis editorial independiente elaborada para lectores del sector. Los hechos y declaraciones originales pertenecen a la fuente enlazada; GRIMM PUMP no afirma representar a dicha entidad.`;
}
function composeEnglish(candidate: Candidate, theme: Row | undefined) { return `## Source facts\n\n${candidate.summary || "The source did not provide enough summary detail to expand the facts without reproducing the original work."}\n\nThis page is an editorial summary. Verify the original publication directly with ${candidate.sourceName}.\n\n## Project context\n\nTeams should review applicability, effective dates, local requirements and site conditions before acting.${theme ? ` Related system: [${asString(theme.product_name)}](${asString(theme.product_url)}).` : ""}\n\n## Original source\n\n${candidate.sourceUrl}\n\n## Editorial disclaimer\n\nOriginal facts remain attributed to the linked source.`; }

async function verifyPublished(site: NewsSite, article: Row) {
  const db = await getDatabase(); const slug = asString(article.slug); const title = asString(article.title); const urls = [{ type: "list", url: `${site.siteUrl}${site.listRoute}` }, { type: "detail", url: `${site.siteUrl}${site.detailRoutePattern.replace("[slug]", slug)}` }, { type: "sitemap", url: `${site.siteUrl}${site.sitemapRoute}` }];
  const results: { type: string; ok: boolean; status: number; url: string }[] = [];
  for (const check of urls) { let status = 0, body = ""; try { const response = await fetch(check.url, { cache: "no-store", signal: AbortSignal.timeout(20000) }); status = response.status; body = await response.text(); } catch { /* failure is recorded below */ }
    const ok = status === 200 && (check.type === "sitemap" ? body.includes(slug) : body.includes(title)); results.push({ type: check.type, ok, status, url: check.url }); await db.execute({ sql: "INSERT INTO industry_news_delivery_checks (id,site_id,article_id,check_type,check_url,http_status,passed,details,checked_at) VALUES (?,?,?,?,?,?,?,?,?)", args: [randomUUID(), site.siteId, asString(article.id), check.type, check.url, status || null, ok ? 1 : 0, JSON.stringify({ titleFound: body.includes(title), slugFound: body.includes(slug) }), iso()] }); }
  return results;
}

export async function publishNewsSite(site: NewsSite) {
  const db = await getDatabase(); const key = await acquireLock(site.siteId, "publish", 30); if (!key) return { siteId: site.siteId, status: "locked" };
  const runKey = cycleKey(48); const started = iso(); const idempotencyKey = `${site.siteId}:${runKey}`;
  try {
    const previous = await db.execute({ sql: "SELECT status,article_id FROM industry_news_publication_runs WHERE site_id=? AND cycle_key=?", args: [site.siteId, runKey] }); if (previous.rows[0]?.status === "published_success") return { siteId: site.siteId, status: "already_published", articleId: previous.rows[0].article_id };
    const runId = randomUUID(); await db.execute({ sql: "INSERT INTO industry_news_publication_runs (id,site_id,cycle_key,status,attempts,started_at,idempotency_key,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT (site_id,cycle_key) DO UPDATE SET status='selecting',attempts=industry_news_publication_runs.attempts+1,started_at=EXCLUDED.started_at,updated_at=EXCLUDED.updated_at,error_code=NULL,error_message=NULL", args: [runId, site.siteId, runKey, "selecting", 1, started, idempotencyKey, started, started] });
    const candidateRows = await db.execute({ sql: "SELECT * FROM industry_news_candidates WHERE site_id=? AND status='candidate' AND used_by_article_id IS NULL AND source_published_at>=? ORDER BY relevance_score DESC,source_published_at DESC LIMIT 1", args: [site.siteId, new Date(Date.now() - site.fallbackCandidateMaxAgeDays * 86400000).toISOString()] }); const row = candidateRows.rows[0]; if (!row) throw new Error("no_eligible_candidate"); const candidate: Candidate = { id: asString(row.id), siteId: asString(row.site_id), title: asString(row.title), summary: asString(row.summary), sourceName: asString(row.source_name), sourceUrl: asString(row.normalized_url), sourcePublishedAt: asString(row.source_published_at), sourceAuthor: row.source_author ? asString(row.source_author) : null, language: row.language ? asString(row.language) : null, relevanceScore: Number(row.relevance_score), contentFingerprint: asString(row.content_fingerprint) };
    const themeRows = await db.execute({ sql: "SELECT * FROM industry_news_theme_windows WHERE site_id=? AND status='active' AND start_at<=? AND end_at>=? ORDER BY start_at DESC LIMIT 1", args: [site.siteId, started, started] }); const theme = themeRows.rows[0];
    const content = site.publicationLanguage === "es" ? composeSpanish(candidate, theme) : composeEnglish(candidate, theme); const articleId = randomUUID(); const slug = slugFrom(candidate.title, candidate.contentFingerprint); const canonical = `${site.siteUrl}${site.detailRoutePattern.replace("[slug]", slug)}`; const deck = candidate.summary.slice(0, 300) || `Actualización atribuida a ${candidate.sourceName}.`;
    await db.execute({ sql: "INSERT INTO industry_news_articles (id,site_id,candidate_id,status,slug,title,deck,content,source_name,source_url,source_published_at,source_author,image_rights_status,editorial_disclaimer,product_url,product_name,seo_title,seo_description,canonical_url,published_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", args: [articleId, site.siteId, candidate.id, "published", slug, candidate.title, deck, content, candidate.sourceName, candidate.sourceUrl, candidate.sourcePublishedAt, candidate.sourceAuthor, "no_external_image_used", "Síntesis editorial independiente; los hechos originales pertenecen a la fuente enlazada.", theme ? asString(theme.product_url) : null, theme ? asString(theme.product_name) : null, candidate.title, deck, canonical, started, started, started] });
    await db.execute({ sql: "UPDATE industry_news_candidates SET status='used',used_by_article_id=?,reserved_cycle_key=?,updated_at=? WHERE id=? AND status='candidate'", args: [articleId, runKey, iso(), candidate.id] });
    const article = { id: articleId, slug, title: candidate.title }; const checks = await verifyPublished(site, article); const passed = checks.every((check) => check.ok);
    await db.execute({ sql: "UPDATE industry_news_publication_runs SET status=?,candidate_id=?,article_id=?,finished_at=?,updated_at=?,error_code=?,error_message=? WHERE site_id=? AND cycle_key=?", args: [passed ? "published_success" : "retry_pending", candidate.id, articleId, iso(), iso(), passed ? null : "frontend_verification_failed", passed ? null : JSON.stringify(checks), site.siteId, runKey] });
    await audit(site.siteId, "news_publish_frontend_verification", "news_article", articleId, passed ? "success" : "failure", { runKey, checks }); return { siteId: site.siteId, status: passed ? "published_success" : "retry_pending", articleId, slug, checks };
  } catch (error) { await db.execute({ sql: "UPDATE industry_news_publication_runs SET status='failed',finished_at=?,updated_at=?,error_code=?,error_message=? WHERE site_id=? AND cycle_key=?", args: [iso(), iso(), error instanceof Error ? error.message : "unknown", error instanceof Error ? error.message : "unknown", site.siteId, runKey] }); await audit(site.siteId, "news_publish_failed", "publication_run", runKey, "failure", { error: error instanceof Error ? error.message : "unknown" }); return { siteId: site.siteId, status: "failed", error: error instanceof Error ? error.message : "unknown" }; } finally { await releaseLock(key); }
}

export async function runNewsIngest() { const sites = await getNewsSites(); return Promise.all(sites.map(ingestNewsSite)); }
export async function runNewsPublish() { const sites = await getNewsSites(); return Promise.all(sites.map(publishNewsSite)); }
