import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { SiteFooter, SiteHeader, JsonLd } from "@/components/site-shell";
import { getDefaultNewsSite, getPublicNewsArticle } from "@/lib/industry-news";

export const dynamic = "force-dynamic";
function date(value: unknown) { return new Intl.DateTimeFormat("es-CL", { dateStyle: "long", timeZone: "America/Santiago" }).format(new Date(String(value))); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const site = await getDefaultNewsSite(); const article = site ? await getPublicNewsArticle(site.siteId, slug) : null; if (!article) return {}; return { title: String(article.seo_title), description: String(article.seo_description), alternates: { canonical: String(article.canonical_url) }, openGraph: { type: "article", locale: "es_CL", title: String(article.seo_title), description: String(article.seo_description), publishedTime: String(article.published_at) } }; }
export default async function NewsArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const site = await getDefaultNewsSite(); const article = site ? await getPublicNewsArticle(site.siteId, slug) : null; if (!site || !article) notFound();
  const sections = String(article.content).split(/\n\n(?=## )/).map((block) => ({ heading: block.startsWith("## ") ? block.slice(3).split("\n")[0] : "", body: block.startsWith("## ") ? block.slice(3).split("\n").slice(1).join("\n") : block }));
  return <><SiteHeader/><main><article className="section blog-article"><div className="shell"><p className="kicker">NOTICIAS DEL SECTOR</p><h1 className="page-title">{String(article.title)}</h1><p className="blog-meta">Publicado por el equipo editorial el {date(article.published_at)} · Fuente original: {String(article.source_name)}</p><p className="page-intro">{String(article.deck)}</p><div className="blog-content news-content">{sections.map((section, index) => <section key={index}>{section.heading ? <h2>{section.heading}</h2> : null}{section.body.split("\n\n").filter(Boolean).map((paragraph, paragraphIndex) => <p key={paragraphIndex}>{paragraph.replace(/^- /, "• ")}</p>)}</section>)}</div><aside className="source-panel"><h2>Fuente y transparencia editorial</h2><dl><div><dt>Fuente original</dt><dd>{String(article.source_name)}</dd></div><div><dt>Fecha original</dt><dd>{date(article.source_published_at)}</dd></div>{article.source_author ? <div><dt>Autor indicado</dt><dd>{String(article.source_author)}</dd></div> : null}</dl><a className="btn btn-secondary" href={String(article.source_url)} target="_blank" rel="noreferrer">Abrir fuente original</a><p>{String(article.editorial_disclaimer)}</p></aside>{article.product_url && article.product_name ? <p className="notice">Contexto de proyecto relacionado: <Link href={String(article.product_url)}>{String(article.product_name)}</Link>.</p> : null}<Link className="card-link" href="/es/noticias">← Volver a Noticias</Link></div></article></main><SiteFooter/><JsonLd data={{ "@context": "https://schema.org", "@type": "NewsArticle", headline: String(article.title), datePublished: String(article.published_at), dateModified: String(article.updated_at), mainEntityOfPage: String(article.canonical_url), author: { "@type": "Organization", name: String(site.defaultAuthorType) }, publisher: { "@type": "Organization", name: site.brandName, url: site.siteUrl }, isBasedOn: String(article.source_url) }}/></>;
}
