"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type Resource = "categories" | "products" | "news" | "leads" | "users" | "settings" | "sync" | "seo" | "audit" | "analytics" | "media" | "forms" | "pages" | "downloads";
type Row = Record<string, unknown>;
type ApiData = { items?: Row[]; pagination?: { page: number; pageSize: number; total: number }; metrics?: Row[]; issues?: Row[]; configured?: boolean; daily?: Row[]; byCountry?: Row[]; totals?: Row };

const meta: Record<Resource, { title: string; description: string; fields: string[]; create?: Record<string, string> }> = {
  categories: { title: "产品分类", description: "管理南美站产品分类、导航展示与排序。", fields: ["name", "slug", "sort_order", "is_enabled", "updated_at"], create: { name: "", slug: "", description: "" } },
  products: { title: "产品管理", description: "管理产品资料、发布状态和面向客户的内容。", fields: ["name", "sku", "slug", "category_name", "status", "updated_at"], create: { name: "", slug: "", sku: "", shortDescription: "", content: "", status: "draft" } },
  news: { title: "新闻管理", description: "维护新闻内容，控制草稿、审核与发布状态。", fields: ["title", "slug", "category_name", "status", "updated_at"], create: { title: "", slug: "", excerpt: "", content: "", status: "draft" } },
  leads: { title: "客户询盘 CRM", description: "客户线索、跟进状态和自动评分。", fields: ["name", "company", "email", "country", "product_interest", "status", "created_at"] },
  users: { title: "账号与权限", description: "为团队成员分配后台角色与最小权限。", fields: ["name", "email", "role", "status", "last_login_at", "created_at"], create: { name: "", email: "", password: "", role: "viewer" } },
  settings: { title: "系统设置", description: "管理网站运行所需的非敏感配置项。", fields: ["key", "value", "updated_at"] },
  sync: { title: "新闻自动化", description: "查看 Search Console 与内容自动化任务的运行记录。", fields: ["source", "run_type", "status", "records_processed", "started_at", "finished_at"] },
  seo: { title: "SEO 管理", description: "查看已同步的 Google Search Console 表现和站内问题。", fields: [] },
  audit: { title: "操作日志", description: "记录后台关键操作，便于追溯与审查。", fields: ["action", "entity_type", "entity_id", "actor_email", "result", "created_at"] },
  analytics: { title: "访问分析", description: "基于真实已保存询盘的转化分析。", fields: [] },
  media: { title: "媒体资源", description: "登记并统一管理网站使用的远程图片与文件资源。", fields: ["filename", "mime_type", "alt_text", "created_at"], create: { filename: "", url: "", mimeType: "image/jpeg", altText: "" } },
  forms: { title: "表单管理", description: "登记表单用途、通知邮箱与启用状态。", fields: ["name", "form_type", "notification_email", "status", "updated_at"], create: { name: "", formType: "contact", notificationEmail: "", status: "active" } },
  pages: { title: "页面管理", description: "管理落地页内容草稿与发布状态。", fields: ["title", "slug", "status", "updated_at"], create: { title: "", slug: "", content: "", status: "draft" } },
  downloads: { title: "下载资料", description: "维护产品手册、技术资料等客户可下载内容。", fields: ["name", "file_url", "category", "status", "updated_at"], create: { name: "", fileUrl: "", category: "", status: "published" } },
};

const labels: Record<string, string> = { name: "名称", title: "标题", slug: "Slug", sku: "SKU", description: "说明", shortDescription: "简短描述", excerpt: "摘要", content: "正文", status: "状态", email: "邮箱", password: "初始密码", role: "角色", key: "配置键", value: "配置值", filename: "文件名", url: "资源 URL", mimeType: "MIME 类型", altText: "替代文本", formType: "表单类型", notificationEmail: "通知邮箱", fileUrl: "文件 URL", category: "分类", company: "公司", country: "国家", product_interest: "意向产品", created_at: "提交时间", updated_at: "更新时间", form_type: "表单类型", notification_email: "通知邮箱", file_url: "文件地址", mime_type: "文件类型", alt_text: "替代文本", records_processed: "处理数量", started_at: "开始时间", finished_at: "结束时间", entity_type: "对象", entity_id: "对象 ID", actor_email: "操作账号" };
const statuses = ["draft", "pending", "published", "scheduled", "offline", "new", "pending_contact", "contacted", "qualified", "quoting", "won", "lost", "active", "disabled"];
function show(value: unknown) { if (value === null || value === undefined || value === "") return "—"; return String(value); }

export function AdminResourceWorkspace({ resource }: { resource: Resource }) {
  const config = meta[resource]; const [data, setData] = useState<ApiData>({}); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [status, setStatus] = useState(""); const [page, setPage] = useState(1); const [open, setOpen] = useState(false); const [editingId, setEditingId] = useState(""); const [form, setForm] = useState(config.create || {}); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const r = await fetch(`/api/admin/${resource}?page=${page}&pageSize=20&q=${encodeURIComponent(query)}&status=${status}`, { cache: "no-store" }); const body = await r.json(); if (!r.ok) throw new Error(body.error || "读取失败"); setData(body.data || {}); } catch (e) { setError(e instanceof Error ? e.message : "读取失败"); } finally { setLoading(false); } }, [page, query, resource, status]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const rows = data.items || [];
  async function create(event: FormEvent) { event.preventDefault(); const r = await fetch(`/api/admin/${resource}${editingId ? `?id=${editingId}` : ""}`, { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await r.json(); if (!r.ok) return setMessage(body.error || "保存失败"); setMessage(editingId ? "已更新" : "已保存"); setOpen(false); setEditingId(""); setForm(config.create || {}); await load(); }
  function editRow(row: Row) { const source = config.create || {}; const next: Record<string, string> = {}; for (const key of Object.keys(source)) { const snake = key.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`); next[key] = show(row[key] ?? row[snake]); } setForm(next); setEditingId(show(row.id)); setOpen(true); }
  async function removeRow(id: string) { if (!confirm("确认删除此记录？")) return; const r = await fetch(`/api/admin/${resource}?id=${id}`, { method: "DELETE" }); if (!r.ok) setMessage("删除失败"); else { setMessage("已删除"); await load(); } }
  async function updateLead(id: string, leadStatus: string) { const r = await fetch(`/api/admin/leads?id=${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: leadStatus }) }); if (!r.ok) setMessage("更新跟进状态失败"); else await load(); }
  async function runSync() { setMessage("正在同步 Search Console…"); const r = await fetch("/api/admin/sync/search-console", { method: "POST" }); const body = await r.json().catch(() => ({})); setMessage(r.ok ? `同步完成：已处理 ${body.data?.records || 0} 条记录` : body.error || "同步失败"); await load(); }
  const canCreate = Boolean(config.create);
  if (resource === "analytics") return <Analytics data={data} loading={loading} error={error} reload={load} />;
  if (resource === "seo") return <Seo data={data} loading={loading} error={error} reload={load} />;
  return <div className="admin-workspace"><header className="admin-page-header"><div><p>{resource === "leads" ? "客户询盘 CRM" : "GRIMM PUMP 后台管理"}</p><h1>{config.title}</h1><span>{config.description}</span></div><div className="header-actions">{resource === "leads" && <button className="logout" onClick={() => window.location.assign("/api/admin/export?type=leads")}>导出线索 CSV</button>}{resource === "sync" && <button className="btn btn-small" onClick={() => void runSync()}>立即同步 Search Console</button>}{canCreate && <button className="btn btn-small" onClick={() => { setEditingId(""); setForm(config.create || {}); setOpen(!open); }}>{open ? "取消" : `新建${config.title}`}</button>}</div></header>{open && <form className="resource-form" onSubmit={create}>{Object.entries(form).map(([key, value]) => <label key={key}>{labels[key] || key}{key === "content" ? <textarea value={value} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /> : key === "status" ? <select value={value} onChange={(e) => setForm({ ...form, [key]: e.target.value })}>{statuses.map((item) => <option key={item} value={item}>{item}</option>)}</select> : key === "role" ? <select value={value} onChange={(e) => setForm({ ...form, [key]: e.target.value })}>{["viewer", "editor", "marketing", "sales", "analyst", "admin", "super_admin"].map((item) => <option key={item}>{item}</option>)}</select> : <input required={!['description','shortDescription','excerpt','content','sku','altText','category','notificationEmail'].includes(key)} type={key === "password" ? "password" : "text"} value={value} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />}</label>)}<button className="btn">{editingId ? "保存修改" : "保存"}</button></form>}{message && <p className="form-success admin-notice">{message}</p>}<div className="admin-panel"><div className="toolbar"><input aria-label="关键词搜索" placeholder="搜索名称、邮箱、国家、产品..." value={query} onChange={(e) => { setPage(1); setQuery(e.target.value); }} />{["products", "news", "leads", "forms", "pages", "downloads"].includes(resource) && <select aria-label="状态筛选" value={status} onChange={(e) => { setPage(1); setStatus(e.target.value); }}><option value="">全部状态</option>{statuses.map((item) => <option key={item}>{item}</option>)}</select>}<button className="logout" onClick={() => void load()}>刷新</button></div>{loading ? <p className="loading">加载中…</p> : error ? <p className="form-error loading">{error}</p> : resource === "leads" ? <LeadList rows={rows} onStatus={updateLead} /> : <Table rows={rows} fields={config.fields} editable={Boolean(config.create)} onEdit={editRow} onDelete={removeRow} />}<div className="pagination"><span>共 {data.pagination?.total || rows.length} 条</span><button className="logout" disabled={page === 1} onClick={() => setPage(page - 1)}>上一页</button><span>第 {page} 页</span><button className="logout" disabled={rows.length < 20} onClick={() => setPage(page + 1)}>下一页</button></div></div></div>;
}

function Table({ rows, fields, editable = false, onEdit, onDelete }: { rows: Row[]; fields: string[]; editable?: boolean; onEdit?: (row: Row) => void; onDelete?: (id: string) => void }) { return <div className="admin-table"><table><thead><tr>{fields.map((field) => <th key={field}>{labels[field] || field}</th>)}{editable && <th>操作</th>}</tr></thead><tbody>{rows.length ? rows.map((row, i) => <tr key={show(row.id || i)}>{fields.map((field) => <td key={field}>{field === "status" ? <em>{show(row[field])}</em> : show(row[field])}</td>)}{editable && <td className="row-actions"><button className="text-action" onClick={() => onEdit?.(row)}>编辑</button><button className="danger-link" onClick={() => onDelete?.(show(row.id))}>删除</button></td>}</tr>) : <tr><td colSpan={fields.length + Number(editable)} className="empty-cell">暂无数据</td></tr>}</tbody></table></div>; }
function LeadList({ rows, onStatus }: { rows: Row[]; onStatus: (id: string, status: string) => Promise<void> }) { return <div className="lead-list">{rows.length ? rows.map((row) => <LeadCard key={show(row.id)} row={row} onStatus={onStatus} />) : <p className="empty-cell">暂无客户询盘</p>}</div>; }
function LeadCard({ row, onStatus }: { row: Row; onStatus: (id: string, status: string) => Promise<void> }) { const [draftStatus, setDraftStatus] = useState(show(row.status)); return <article className="lead-card"><div><h2>{show(row.name)} <em>{show(row.status)}</em></h2><p>{show(row.email)} · {show(row.country)} · {show(row.company)}</p><b>{show(row.product_interest)}</b><small>{show(row.created_at)}</small></div><aside><label>跟进状态<select value={draftStatus} onChange={(e) => setDraftStatus(e.target.value)}>{statuses.filter((s) => ["new","pending_contact","contacted","qualified","quoting","won","lost"].includes(s)).map((s) => <option key={s}>{s}</option>)}</select></label><p>销售负责人：{show(row.assignee_name)}</p><button className="btn btn-small" onClick={() => void onStatus(show(row.id), draftStatus)}>保存跟进</button></aside></article>; }
function Analytics({ data, loading, error, reload }: { data: ApiData; loading: boolean; error: string; reload: () => Promise<void> }) { return <section className="admin-panel insight-panel"><div className="table-title"><div><h2>询盘转化分析</h2><span>数据直接来自网站已保存的真实客户询盘</span></div><button className="logout" onClick={() => void reload()}>刷新</button></div>{loading ? <p className="loading">加载中…</p> : error ? <p className="form-error loading">{error}</p> : <><div className="stat-row seo-stat"><article><span>全部询盘</span><b>{show(data.totals?.leads)}</b></article><article><span>有效商机</span><b>{show(data.totals?.qualified)}</b></article><article><span>来源国家</span><b>{data.byCountry?.length || 0}</b></article></div><Table rows={data.daily || []} fields={["metric_date", "leads", "countries"]} /><div className="table-title"><h2>国家来源</h2></div><Table rows={data.byCountry || []} fields={["country", "leads"]} /></>}</section>; }
function Seo({ data, loading, error, reload }: { data: ApiData; loading: boolean; error: string; reload: () => Promise<void> }) { return <section className="admin-panel insight-panel"><div className="table-title"><div><h2>SEO 数据</h2><span>Search Console 表现与站内问题中心</span></div><button className="logout" onClick={() => void reload()}>刷新</button></div>{loading ? <p className="loading">加载中…</p> : error ? <p className="form-error loading">{error}</p> : <><div className="stat-row seo-stat"><article><span>Search Console</span><b>{data.configured ? "已接入" : "未配置"}</b></article><article><span>近 30 日记录</span><b>{data.metrics?.length || 0}</b></article><article><span>待处理问题</span><b>{data.issues?.length || 0}</b></article></div><Table rows={data.metrics?.length ? data.metrics : data.issues || []} fields={data.metrics?.length ? ["metric_date", "clicks", "impressions", "ctr", "position"] : ["issue_type", "severity", "page_path", "message", "status"]} /></>}</section>; }
