"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Resource = "categories" | "products" | "news" | "leads" | "users" | "settings" | "sync" | "seo" | "audit" | "analytics";
type ApiData = { items?: Record<string, unknown>[]; pagination?: { page: number; pageSize: number; total: number }; metrics?: Record<string, unknown>[]; issues?: Record<string, unknown>[]; configured?: boolean; daily?: Record<string, unknown>[]; byCountry?: Record<string, unknown>[]; totals?: Record<string, unknown> };

const labels: Record<Resource, string> = { categories: "产品分类", products: "产品", news: "新闻", leads: "客户表单", users: "用户", settings: "系统设置", sync: "数据同步", seo: "SEO 数据", audit: "操作日志", analytics: "访问分析" };
const fields: Record<string, string[]> = { categories: ["name", "slug", "parent_id", "is_enabled", "updated_at"], products: ["name", "sku", "slug", "category_name", "status", "updated_at"], news: ["title", "slug", "category_name", "status", "updated_at"], leads: ["name", "company", "email", "country", "product_interest", "assignee_name", "status", "created_at"], users: ["name", "email", "role", "status", "last_login_at", "created_at"], sync: ["source", "run_type", "status", "records_processed", "started_at", "finished_at", "error_message"], audit: ["action", "entity_type", "entity_id", "actor_email", "result", "created_at"] };
const initialForms: Record<string, Record<string, string>> = { categories: { name: "", slug: "", description: "" }, products: { name: "", slug: "", sku: "", shortDescription: "", content: "", status: "draft" }, news: { title: "", slug: "", excerpt: "", content: "", status: "draft" }, users: { name: "", email: "", password: "", role: "viewer" } };

function display(value: unknown) { if (value === null || value === undefined || value === "") return "—"; if (typeof value === "object") return JSON.stringify(value); return String(value); }
function label(field: string) { return ({ name: "名称", title: "标题", slug: "Slug", sku: "SKU", description: "简介", shortDescription: "简短描述", excerpt: "摘要", content: "正文", status: "状态", email: "邮箱", password: "初始密码", role: "角色", metric_date: "日期", leads: "询盘数", countries: "国家数", country: "国家" } as Record<string, string>)[field] || field; }

export function AdminResourceWorkspace({ resource }: { resource: Resource }) {
  const [data, setData] = useState<ApiData>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [showCreate, setShowCreate] = useState(false); const [form, setForm] = useState(initialForms[resource] || {}); const [message, setMessage] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/admin/${resource}?page=${page}&pageSize=${pageSize}&q=${encodeURIComponent(query)}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "读取失败"); setData(body.data || {}); } catch (cause) { setError(cause instanceof Error ? cause.message : "读取失败"); } finally { setLoading(false); } }, [page, pageSize, query, resource]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const tableFields = useMemo(() => fields[resource] || [], [resource]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); const payload: Record<string, unknown> = { ...form }; if (resource === "categories") payload.enabled = true; try { const response = await fetch(`/api/admin/${resource}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "保存失败"); setMessage("已保存。"); setShowCreate(false); setForm(initialForms[resource] || {}); await load(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "保存失败"); } }
  async function updateLead(id: string, status: string) { const response = await fetch(`/api/admin/leads?id=${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (response.ok) await load(); else setMessage("状态更新失败。"); }
  async function runSearchConsoleSync() { setMessage("正在请求 Search Console 同步…"); const response = await fetch("/api/admin/sync/search-console", { method: "POST" }); const body = await response.json().catch(() => ({})); setMessage(response.ok ? `同步完成：已处理 ${body.data.records} 条日期记录。` : (body.error || "同步失败。")); await load(); }
  async function remove(id: string) { if (!confirm("确认将此记录移入回收状态？")) return; const response = await fetch(`/api/admin/${resource}?id=${id}`, { method: "DELETE" }); if (response.ok) { setMessage("已移入回收状态。"); await load(); } else setMessage("删除失败。"); }
  if (resource === "analytics") return <section className="admin-panel"><div className="table-title"><div><h2>询盘转化分析</h2><span>数据直接来自网站已保存的真实客户表单</span></div><button className="logout" onClick={() => void load()}>刷新</button></div>{loading ? <p className="loading">加载中…</p> : error ? <p className="form-error">{error}</p> : <><div className="stat-row seo-stat"><article><span>全部询盘</span><b>{String(data.totals?.leads || 0)}</b><small>未删除的客户提交</small></article><article><span>有效商机</span><b>{String(data.totals?.qualified || 0)}</b><small>已确认、报价或成交</small></article><article><span>来源国家</span><b>{data.byCountry?.length || 0}</b><small>真实表单国家分布</small></article></div><DataTable rows={data.daily || []} tableFields={["metric_date", "leads", "countries"]} /><div className="table-title"><h2>国家来源</h2></div><DataTable rows={data.byCountry || []} tableFields={["country", "leads"]} /></>}</section>;
  if (resource === "seo") return <section className="admin-panel"><div className="table-title"><div><h2>SEO 数据</h2><span>Search Console 表现与站内问题中心</span></div><button className="logout" onClick={() => void load()}>刷新</button></div>{loading ? <p className="loading">加载中…</p> : error ? <p className="form-error">{error}</p> : <><div className="stat-row seo-stat"><article><span>Search Console</span><b>{data.configured ? "已接入" : "未配置"}</b><small>仅显示真实 API 同步数据</small></article><article><span>近 30 日记录</span><b>{data.metrics?.length || 0}</b><small>按日聚合</small></article><article><span>待处理问题</span><b>{data.issues?.length || 0}</b><small>站内 SEO 检测结果</small></article></div><DataTable rows={[...(data.metrics || []), ...(data.issues || [])]} tableFields={data.metrics?.length ? ["metric_date", "clicks", "impressions", "ctr", "position"] : ["issue_type", "severity", "page_path", "message", "status", "detected_at"]} /></>}</section>;
  return <section className="admin-panel"><div className="table-title"><div><h2>{labels[resource]}</h2><span>服务端分页、搜索、权限校验与审计记录</span></div><div className="header-actions">{resource === "sync" && <button className="btn btn-small" onClick={() => void runSearchConsoleSync()}>立即同步 Search Console</button>}{initialForms[resource] && <button className="btn btn-small" onClick={() => setShowCreate(!showCreate)}>{showCreate ? "取消" : `新建${labels[resource]}`}</button>}</div></div>{showCreate && <form className="resource-form" onSubmit={create}>{Object.entries(form).map(([key, value]) => <label key={key}>{label(key)}{key === "content" ? <textarea value={value} onChange={(e) => setForm({ ...form, [key]: e.target.value })} /> : key === "status" ? <select value={value} onChange={(e) => setForm({ ...form, [key]: e.target.value })}><option value="draft">草稿</option><option value="pending">待审核</option><option value="published">已发布</option><option value="scheduled">定时发布</option><option value="offline">已下架</option></select> : key === "role" ? <select value={value} onChange={(e) => setForm({ ...form, [key]: e.target.value })}>{["viewer", "editor", "marketing", "sales", "analyst", "admin", "super_admin"].map((role) => <option key={role}>{role}</option>)}</select> : <input type={key === "password" ? "password" : "text"} value={value} required={!["description", "shortDescription", "excerpt", "content", "sku"].includes(key)} onChange={(e) => setForm({ ...form, [key]: e.target.value })} />}</label>)}<button className="btn">保存</button></form>}{message && <p className="form-success">{message}</p>}<div className="toolbar"><input aria-label="关键词搜索" placeholder="搜索关键词" value={query} onChange={(event) => { setPage(1); setQuery(event.target.value); }} /><select aria-label="每页数量" value={pageSize} onChange={(event) => { setPage(1); setPageSize(Number(event.target.value)); }}><option value={10}>10 条/页</option><option value={20}>20 条/页</option><option value={50}>50 条/页</option><option value={100}>100 条/页</option></select><button className="logout" onClick={() => void load()}>刷新</button></div>{loading ? <p className="loading">加载中…</p> : error ? <p className="form-error">{error}</p> : <><DataTable rows={data.items || []} tableFields={tableFields} onDelete={resource === "categories" || resource === "products" || resource === "news" || resource === "leads" ? remove : undefined} onLeadStatus={resource === "leads" ? updateLead : undefined} /><div className="pagination"><span>共 {data.pagination?.total || 0} 条</span><button className="logout" disabled={page <= 1} onClick={() => setPage(page - 1)}>上一页</button><span>第 {page} 页</span><button className="logout" disabled={(data.items || []).length < pageSize} onClick={() => setPage(page + 1)}>下一页</button></div></>}</section>;
}

function DataTable({ rows, tableFields, onDelete, onLeadStatus }: { rows: Record<string, unknown>[]; tableFields: string[]; onDelete?: (id: string) => void; onLeadStatus?: (id: string, status: string) => void }) { return <div className="admin-table"><table><thead><tr>{tableFields.map((field) => <th key={field}>{label(field)}</th>)}{(onDelete || onLeadStatus) && <th>操作</th>}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={String(row.id || index)}>{tableFields.map((field) => <td key={field}>{field === "status" ? <em>{display(row[field])}</em> : display(row[field])}</td>)}{(onDelete || onLeadStatus) && <td className="row-actions">{onLeadStatus && <select defaultValue={String(row.status || "new")} onChange={(event) => onLeadStatus(String(row.id), event.target.value)}>{["new", "pending_contact", "contacted", "qualified", "invalid", "quoting", "won", "lost", "spam", "archived"].map((status) => <option key={status}>{status}</option>)}</select>}{onDelete && <button className="danger-link" onClick={() => onDelete(String(row.id))}>删除</button>}</td>}</tr>) : <tr><td colSpan={tableFields.length + 1} className="empty-cell">暂无数据</td></tr>}</tbody></table></div>; }
