"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Data = { profile?: Record<string, unknown>; leads?: Record<string, unknown>[]; totals?: Record<string, unknown>; events?: Record<string, unknown>[]; pagination?: { page: number; pageSize: number; total: number } };
const presets = [["all", "全部"], ["today", "今天"], ["week", "本周"], ["month", "本月"], ["custom", "自定义"]] as const;
const format = (value: unknown) => value ? new Intl.DateTimeFormat("zh-CN", { timeZone: "America/Santiago", dateStyle: "medium", timeStyle: "short" }).format(new Date(String(value))) : "—";

export function CustomerDetail({ customerId }: { customerId: string }) {
  const [preset, setPreset] = useState("all"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [page, setPage] = useState(1); const [data, setData] = useState<Data>({}); const [error, setError] = useState("");
  const load = useCallback(async () => { const query = new URLSearchParams({ preset, page: String(page), pageSize: "50" }); if (preset === "custom") { query.set("from", from); query.set("to", to); } const response = await fetch(`/api/admin/customers/${customerId}?${query}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) setError(body.error || "读取失败"); else { setError(""); setData(body.data); } }, [customerId, from, page, preset, to]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const profile = data.profile || {}; const events = data.events || [];
  return <div className="admin-workspace customer-detail"><Link href="/admin/customers" className="back-link">← 返回客户中心</Link><header className="admin-page-header"><div><p>客户 360° 档案</p><h1>{String(profile.display_name || "客户")}</h1><span>{String(profile.company || "—")} · {String(profile.country || "—")} · 首次识别 {format(profile.first_seen_at)}</span></div></header><section className="stat-row seo-stat"><article><span>浏览页数</span><b>{String(data.totals?.page_views ?? 0)}</b></article><article><span>访问会话</span><b>{String(data.totals?.sessions ?? 0)}</b></article><article><span>关联询盘</span><b>{String(data.leads?.length ?? 0)}</b></article></section><div className="admin-panel filter-panel"><div className="filter-row"><span>访问时间（智利时间）</span>{presets.map(([value, label]) => <button key={value} className={preset === value ? "filter-active" : "filter-chip"} onClick={() => { setPreset(value); setPage(1); }}>{label}</button>)}</div>{preset === "custom" && <div className="filter-row"><label>开始<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label>结束<input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><button className="btn btn-small" onClick={() => void load()}>查询</button></div>}</div>{error ? <p className="form-error">{error}</p> : <><section className="admin-panel customer-leads"><h2>关联询盘</h2>{data.leads?.length ? data.leads.map((lead) => <article key={String(lead.id)}><b>{String(lead.product_interest || "产品咨询")}</b><span>{String(lead.status)} · {format(lead.created_at)}</span><small>提交页：{String(lead.source_path || "—")}</small></article>) : <p className="empty-cell">暂无关联询盘</p>}</section><section className="admin-panel"><h2>访问路径</h2><p className="detail-note">仅展示新访问追踪启用后的真实页面路径；不会补造历史浏览记录。</p><ol className="journey-list">{events.length ? events.map((event) => <li key={String(event.id)}><time>{format(event.occurred_at)}</time><b>{String(event.page_title || event.page_path)}</b><span>{String(event.page_path)}</span>{event.referrer_path ? <small>来自 {String(event.referrer_path)}</small> : null}</li>) : <li className="empty-cell">此时间范围内没有已记录的路径。</li>}</ol><div className="pagination"><span>共 {data.pagination?.total || 0} 条</span><button className="logout" disabled={page === 1} onClick={() => setPage(page - 1)}>上一页</button><span>第 {page} 页</span><button className="logout" disabled={events.length < 50} onClick={() => setPage(page + 1)}>下一页</button></div></section></>}</div>;
}
