import { randomUUID } from "node:crypto";
import { hash } from "bcryptjs";
import { z } from "zod";
import { fail, ok, pagination, requireAdmin } from "@/lib/admin-api";
import { getDatabase, writeAudit } from "@/lib/database";

const resourcePermission = {
  categories: { read: "products:view", write: "products:write", remove: "products:delete" }, products: { read: "products:view", write: "products:write", remove: "products:delete" },
  news: { read: "news:view", write: "news:write", remove: "news:delete" }, leads: { read: "leads:view", write: "leads:write", remove: "leads:write" },
  users: { read: "users:manage", write: "users:manage", remove: "users:manage" }, settings: { read: "settings:manage", write: "settings:manage", remove: "settings:manage" },
  sync: { read: "seo:view", write: "seo:sync", remove: "seo:sync" }, audit: { read: "audit:view", write: "audit:view", remove: "audit:view" }, seo: { read: "seo:view", write: "seo:sync", remove: "seo:sync" }, analytics: { read: "analytics:view", write: "analytics:view", remove: "analytics:view" },
  media: { read: "products:view", write: "products:write", remove: "products:delete" }, forms: { read: "leads:view", write: "leads:write", remove: "leads:write" }, pages: { read: "settings:manage", write: "settings:manage", remove: "settings:manage" }, downloads: { read: "products:view", write: "products:write", remove: "products:delete" },
} as const;
type Resource = keyof typeof resourcePermission;
const categorySchema = z.object({ name: z.string().trim().min(2).max(120), slug: z.string().trim().regex(/^[a-z0-9-]+$/).max(160), parentId: z.string().uuid().nullable().optional(), description: z.string().trim().max(4000).optional(), sortOrder: z.number().int().min(0).max(100000).default(0), enabled: z.boolean().default(true), showInNav: z.boolean().default(false) });
const productSchema = z.object({ sku: z.string().trim().max(120).optional(), categoryId: z.string().uuid().nullable().optional(), name: z.string().trim().min(2).max(180), slug: z.string().trim().regex(/^[a-z0-9-]+$/).max(180), shortDescription: z.string().trim().max(1000).optional(), content: z.string().trim().max(60000).optional(), technicalSpecs: z.record(z.string(), z.string()).optional(), status: z.enum(["draft", "pending", "published", "scheduled", "offline", "archived"]).default("draft"), isFeatured: z.boolean().default(false) });
const newsSchema = z.object({ categoryId: z.string().uuid().nullable().optional(), title: z.string().trim().min(2).max(220), slug: z.string().trim().regex(/^[a-z0-9-]+$/).max(180), excerpt: z.string().trim().max(1000).optional(), content: z.string().trim().max(80000).optional(), status: z.enum(["draft", "pending", "published", "scheduled", "offline", "archived"]).default("draft"), isFeatured: z.boolean().default(false) });
const leadSchema = z.object({ status: z.enum(["new", "pending_contact", "contacted", "qualified", "invalid", "quoting", "won", "lost", "spam", "archived"]).optional(), assigneeId: z.string().uuid().nullable().optional(), tags: z.array(z.string().trim().min(1).max(40)).max(20).optional(), note: z.string().trim().min(1).max(3000).optional() });
const userSchema = z.object({ email: z.string().trim().email().max(160), name: z.string().trim().min(2).max(80), password: z.string().min(12).max(256), role: z.enum(["super_admin", "admin", "editor", "marketing", "sales", "analyst", "viewer"]) });
const settingSchema = z.object({ values: z.record(z.string(), z.string().max(10000)) });
const mediaSchema = z.object({ filename: z.string().trim().min(2).max(180), url: z.string().url().max(2000), mimeType: z.string().trim().min(3).max(120).default("image/jpeg"), altText: z.string().trim().max(300).optional() });
const pageSchema = z.object({ title: z.string().trim().min(2).max(180), slug: z.string().trim().regex(/^[a-z0-9-]+$/).max(180), content: z.string().trim().max(60000).optional(), status: z.enum(["draft", "published", "offline"]).default("draft") });
const downloadSchema = z.object({ name: z.string().trim().min(2).max(180), fileUrl: z.string().url().max(2000), category: z.string().trim().max(100).optional(), status: z.enum(["draft", "published", "offline"]).default("published") });
const formSchema = z.object({ name: z.string().trim().min(2).max(160), formType: z.string().trim().min(2).max(80).default("contact"), status: z.enum(["active", "disabled"]).default("active"), notificationEmail: z.string().email().max(160).optional() });

function isResource(value: string): value is Resource { return value in resourcePermission; }
function idFrom(request: Request) { return new URL(request.url).searchParams.get("id"); }

export async function GET(request: Request, context: RouteContext<"/api/admin/[resource]">) {
  const { resource } = await context.params;
  if (!isResource(resource)) return fail("未知的后台资源。", 404);
  const auth = await requireAdmin(resourcePermission[resource].read); if ("response" in auth) return auth.response;
  try {
    const db = await getDatabase(); const url = new URL(request.url); const { page, pageSize, offset } = pagination(url.searchParams); const q = (url.searchParams.get("q") || "").trim().slice(0, 120); const status = (url.searchParams.get("status") || "").trim().slice(0, 40);
    let sql = ""; let countSql = ""; let args: (string | number | null)[] = []; let countArgs: (string | number | null)[] = [];
    if (resource === "categories") { sql = "SELECT id,name,slug,parent_id,sort_order,is_enabled,show_in_nav,updated_at FROM product_categories WHERE deleted_at IS NULL AND (?='' OR name LIKE ? OR slug LIKE ?) ORDER BY sort_order,id LIMIT ? OFFSET ?"; countSql = "SELECT COUNT(*) AS total FROM product_categories WHERE deleted_at IS NULL AND (?='' OR name LIKE ? OR slug LIKE ?)"; args = [q, `%${q}%`, `%${q}%`, pageSize, offset]; countArgs = [q, `%${q}%`, `%${q}%`]; }
    if (resource === "products") { sql = "SELECT p.id,p.sku,p.category_id,p.status,p.is_featured,p.updated_at,t.name,t.slug,c.name AS category_name FROM products p LEFT JOIN product_translations t ON t.product_id=p.id AND t.locale='es' LEFT JOIN product_categories c ON c.id=p.category_id WHERE p.deleted_at IS NULL AND (?='' OR t.name LIKE ? OR p.sku LIKE ? OR t.slug LIKE ?) AND (?='' OR p.status=?) ORDER BY p.updated_at DESC LIMIT ? OFFSET ?"; countSql = "SELECT COUNT(*) AS total FROM products p LEFT JOIN product_translations t ON t.product_id=p.id AND t.locale='es' WHERE p.deleted_at IS NULL AND (?='' OR t.name LIKE ? OR p.sku LIKE ? OR t.slug LIKE ?) AND (?='' OR p.status=?)"; args = [q, `%${q}%`, `%${q}%`, `%${q}%`, status, status, pageSize, offset]; countArgs = [q, `%${q}%`, `%${q}%`, `%${q}%`, status, status]; }
    if (resource === "news") { sql = "SELECT n.id,n.category_id,n.status,n.is_featured,n.updated_at,t.title,t.slug,c.name AS category_name FROM news_articles n LEFT JOIN news_translations t ON t.article_id=n.id AND t.locale='es' LEFT JOIN news_categories c ON c.id=n.category_id WHERE n.deleted_at IS NULL AND (?='' OR t.title LIKE ? OR t.slug LIKE ?) AND (?='' OR n.status=?) ORDER BY n.updated_at DESC LIMIT ? OFFSET ?"; countSql = "SELECT COUNT(*) AS total FROM news_articles n LEFT JOIN news_translations t ON t.article_id=n.id AND t.locale='es' WHERE n.deleted_at IS NULL AND (?='' OR t.title LIKE ? OR t.slug LIKE ?) AND (?='' OR n.status=?)"; args = [q, `%${q}%`, `%${q}%`, status, status, pageSize, offset]; countArgs = [q, `%${q}%`, `%${q}%`, status, status]; }
    if (resource === "leads") { sql = "SELECT l.id,l.name,l.company,l.email,l.country,l.product_interest,l.status,l.created_at,u.name AS assignee_name FROM leads l LEFT JOIN users u ON u.id=l.assignee_id WHERE l.deleted_at IS NULL AND (?='' OR l.name LIKE ? OR l.company LIKE ? OR l.email LIKE ? OR l.country LIKE ?) AND (?='' OR l.status=?) ORDER BY l.created_at DESC LIMIT ? OFFSET ?"; countSql = "SELECT COUNT(*) AS total FROM leads l WHERE l.deleted_at IS NULL AND (?='' OR l.name LIKE ? OR l.company LIKE ? OR l.email LIKE ? OR l.country LIKE ?) AND (?='' OR l.status=?)"; args = [q, `%${q}%`, `%${q}%`, `%${q}%`, `%${q}%`, status, status, pageSize, offset]; countArgs = [q, `%${q}%`, `%${q}%`, `%${q}%`, `%${q}%`, status, status]; }
    if (resource === "users") { sql = "SELECT id,email,name,role,status,last_login_at,created_at FROM users WHERE (?='' OR email LIKE ? OR name LIKE ?) ORDER BY created_at DESC LIMIT ? OFFSET ?"; countSql = "SELECT COUNT(*) AS total FROM users WHERE (?='' OR email LIKE ? OR name LIKE ?)"; args = [q, `%${q}%`, `%${q}%`, pageSize, offset]; countArgs = [q, `%${q}%`, `%${q}%`]; }
    if (resource === "media") { sql = "SELECT id,filename,url,mime_type,byte_size,alt_text,created_at FROM media_assets WHERE deleted_at IS NULL AND (?='' OR filename LIKE ? OR alt_text LIKE ?) ORDER BY created_at DESC LIMIT ? OFFSET ?"; countSql = "SELECT COUNT(*) AS total FROM media_assets WHERE deleted_at IS NULL AND (?='' OR filename LIKE ? OR alt_text LIKE ?)"; args = [q, `%${q}%`, `%${q}%`, pageSize, offset]; countArgs = [q, `%${q}%`, `%${q}%`]; }
    if (resource === "pages") { sql = "SELECT id,title,slug,status,updated_at FROM site_pages WHERE deleted_at IS NULL AND (?='' OR title LIKE ? OR slug LIKE ?) ORDER BY updated_at DESC LIMIT ? OFFSET ?"; countSql = "SELECT COUNT(*) AS total FROM site_pages WHERE deleted_at IS NULL AND (?='' OR title LIKE ? OR slug LIKE ?)"; args = [q, `%${q}%`, `%${q}%`, pageSize, offset]; countArgs = [q, `%${q}%`, `%${q}%`]; }
    if (resource === "downloads") { sql = "SELECT id,name,file_url,category,status,updated_at FROM download_assets WHERE deleted_at IS NULL AND (?='' OR name LIKE ? OR category LIKE ?) ORDER BY updated_at DESC LIMIT ? OFFSET ?"; countSql = "SELECT COUNT(*) AS total FROM download_assets WHERE deleted_at IS NULL AND (?='' OR name LIKE ? OR category LIKE ?)"; args = [q, `%${q}%`, `%${q}%`, pageSize, offset]; countArgs = [q, `%${q}%`, `%${q}%`]; }
    if (resource === "forms") { sql = "SELECT id,name,form_type,status,notification_email,updated_at FROM form_configurations WHERE deleted_at IS NULL AND (?='' OR name LIKE ? OR form_type LIKE ?) ORDER BY updated_at DESC LIMIT ? OFFSET ?"; countSql = "SELECT COUNT(*) AS total FROM form_configurations WHERE deleted_at IS NULL AND (?='' OR name LIKE ? OR form_type LIKE ?)"; args = [q, `%${q}%`, `%${q}%`, pageSize, offset]; countArgs = [q, `%${q}%`, `%${q}%`]; }
    if (resource === "settings") { const rows = await db.execute("SELECT key,value,is_secret,updated_at FROM system_settings ORDER BY key"); return ok({ items: rows.rows.map((row) => ({ ...row, value: Number(row.is_secret) ? "已配置" : row.value })) }); }
    if (resource === "sync") { const rows = await db.execute({ sql: "SELECT id,source,run_type,status,started_at,finished_at,records_processed,error_code,error_message FROM sync_runs ORDER BY started_at DESC LIMIT ? OFFSET ?", args: [pageSize, offset] }); const count = await db.execute("SELECT COUNT(*) AS total FROM sync_runs"); return ok({ items: rows.rows, pagination: { page, pageSize, total: Number(count.rows[0]?.total || 0) } }); }
    if (resource === "audit") { const rows = await db.execute({ sql: "SELECT a.id,a.action,a.entity_type,a.entity_id,a.result,a.created_at,u.email AS actor_email FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_id ORDER BY a.created_at DESC LIMIT ? OFFSET ?", args: [pageSize, offset] }); const count = await db.execute("SELECT COUNT(*) AS total FROM audit_logs"); return ok({ items: rows.rows, pagination: { page, pageSize, total: Number(count.rows[0]?.total || 0) } }); }
    if (resource === "seo") { const metrics = await db.execute("SELECT metric_date, SUM(clicks) AS clicks, SUM(impressions) AS impressions, CASE WHEN SUM(impressions)>0 THEN SUM(clicks)*1.0/SUM(impressions) ELSE 0 END AS ctr, AVG(position) AS position FROM seo_metrics GROUP BY metric_date ORDER BY metric_date DESC LIMIT 30"); const issues = await db.execute("SELECT id,issue_type,severity,page_path,message,status,detected_at FROM seo_issues WHERE status!='resolved' ORDER BY detected_at DESC LIMIT 50"); return ok({ metrics: metrics.rows, issues: issues.rows, configured: Boolean(process.env.GOOGLE_SERVICE_ACCOUNT_JSON) }); }
    if (resource === "analytics") { const daily = await db.execute("SELECT SUBSTR(created_at,1,10) AS metric_date, COUNT(*) AS leads, COUNT(DISTINCT country) AS countries FROM leads WHERE deleted_at IS NULL GROUP BY SUBSTR(created_at,1,10) ORDER BY metric_date DESC LIMIT 30"); const byCountry = await db.execute("SELECT country, COUNT(*) AS leads FROM leads WHERE deleted_at IS NULL GROUP BY country ORDER BY leads DESC LIMIT 12"); const totals = await db.execute("SELECT COUNT(*) AS leads, SUM(CASE WHEN status IN ('qualified','quoting','won') THEN 1 ELSE 0 END) AS qualified FROM leads WHERE deleted_at IS NULL"); return ok({ daily: daily.rows, byCountry: byCountry.rows, totals: totals.rows[0] || { leads: 0, qualified: 0 } }); }
    const rows = await db.execute({ sql, args }); const count = await db.execute({ sql: countSql, args: countArgs });
    return ok({ items: rows.rows, pagination: { page, pageSize, total: Number(count.rows[0]?.total || 0) } });
  } catch { return fail("读取数据失败，请检查数据库连接。", 503); }
}

export async function POST(request: Request, context: RouteContext<"/api/admin/[resource]">) {
  const { resource } = await context.params;
  if (!isResource(resource)) return fail("未知的后台资源。", 404);
  const auth = await requireAdmin(resourcePermission[resource].write); if ("response" in auth) return auth.response;
  try {
    const body = await request.json(); const db = await getDatabase(); const now = new Date().toISOString(); let id: string = randomUUID();
    if (resource === "categories") { const data = categorySchema.parse(body); if (data.parentId === id) return fail("分类不能设置自己为父级。"); await db.execute({ sql: "INSERT INTO product_categories (id,name,slug,parent_id,description,sort_order,is_enabled,show_in_nav,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)", args: [id, data.name, data.slug, data.parentId || null, data.description || null, data.sortOrder, data.enabled ? 1 : 0, data.showInNav ? 1 : 0, now, now] }); }
    else if (resource === "products") { const data = productSchema.parse(body); await db.execute({ sql: "INSERT INTO products (id,sku,category_id,status,is_featured,technical_specs,created_by,updated_by,created_at,updated_at,published_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)", args: [id, data.sku || null, data.categoryId || null, data.status, data.isFeatured ? 1 : 0, data.technicalSpecs ? JSON.stringify(data.technicalSpecs) : null, auth.session.userId, auth.session.userId, now, now, data.status === "published" ? now : null] }); await db.execute({ sql: "INSERT INTO product_translations (id,product_id,locale,name,slug,short_description,content,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)", args: [randomUUID(), id, "es", data.name, data.slug, data.shortDescription || null, data.content || null, now, now] }); }
    else if (resource === "news") { const data = newsSchema.parse(body); await db.execute({ sql: "INSERT INTO news_articles (id,category_id,status,is_featured,author_id,created_at,updated_at,published_at) VALUES (?,?,?,?,?,?,?,?)", args: [id, data.categoryId || null, data.status, data.isFeatured ? 1 : 0, auth.session.userId, now, now, data.status === "published" ? now : null] }); await db.execute({ sql: "INSERT INTO news_translations (id,article_id,locale,title,slug,excerpt,content,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)", args: [randomUUID(), id, "es", data.title, data.slug, data.excerpt || null, data.content || null, now, now] }); }
    else if (resource === "users") { const data = userSchema.parse(body); await db.execute({ sql: "INSERT INTO users (id,email,name,password_hash,role,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)", args: [id, data.email.toLowerCase(), data.name, await hash(data.password, 12), data.role, "active", now, now] }); }
    else if (resource === "media") { const data = mediaSchema.parse(body); await db.execute({ sql: "INSERT INTO media_assets (id,storage_key,url,filename,mime_type,byte_size,alt_text,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)", args: [id, `external/${id}`, data.url, data.filename, data.mimeType, 0, data.altText || null, auth.session.userId, now] }); }
    else if (resource === "pages") { const data = pageSchema.parse(body); await db.execute({ sql: "INSERT INTO site_pages (id,title,slug,content,status,created_by,updated_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)", args: [id, data.title, data.slug, data.content || null, data.status, auth.session.userId, auth.session.userId, now, now] }); }
    else if (resource === "downloads") { const data = downloadSchema.parse(body); await db.execute({ sql: "INSERT INTO download_assets (id,name,file_url,category,status,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)", args: [id, data.name, data.fileUrl, data.category || null, data.status, auth.session.userId, now, now] }); }
    else if (resource === "forms") { const data = formSchema.parse(body); await db.execute({ sql: "INSERT INTO form_configurations (id,name,form_type,status,notification_email,created_at,updated_at) VALUES (?,?,?,?,?,?,?)", args: [id, data.name, data.formType, data.status, data.notificationEmail || null, now, now] }); }
    else if (resource === "settings") { const data = settingSchema.parse(body); for (const [key, value] of Object.entries(data.values)) await db.execute({ sql: "INSERT INTO system_settings (key,value,is_secret,updated_by,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_by=excluded.updated_by,updated_at=excluded.updated_at", args: [key, value, 0, auth.session.userId, now] }); id = "settings"; }
    else return fail("该资源不支持新建操作。", 405);
    await writeAudit({ action: "create", entityType: resource, entityId: id, actorId: auth.session.userId, details: { resource } }); return ok({ id }, 201);
  } catch (error) { if (error instanceof z.ZodError) return fail("提交数据校验失败。", 400, error.flatten().fieldErrors); return fail("保存失败，可能存在重复的 Slug、SKU 或邮箱。", 400); }
}

export async function PATCH(request: Request, context: RouteContext<"/api/admin/[resource]">) {
  const { resource } = await context.params; if (!isResource(resource)) return fail("未知的后台资源。", 404);
  const auth = await requireAdmin(resourcePermission[resource].write); if ("response" in auth) return auth.response;
  const id = idFrom(request); if (!id) return fail("缺少记录标识。", 400);
  try {
    const body = await request.json(); const db = await getDatabase(); const now = new Date().toISOString();
    if (resource === "pages") { const data = pageSchema.partial().parse(body); await db.execute({ sql: "UPDATE site_pages SET title=COALESCE(?,title),slug=COALESCE(?,slug),content=COALESCE(?,content),status=COALESCE(?,status),updated_by=?,updated_at=? WHERE id=? AND deleted_at IS NULL", args: [data.title || null, data.slug || null, data.content || null, data.status || null, auth.session.userId, now, id] }); await writeAudit({ action: "update", entityType: resource, entityId: id, actorId: auth.session.userId }); return ok({ id }); }
    if (resource === "downloads") { const data = downloadSchema.partial().parse(body); await db.execute({ sql: "UPDATE download_assets SET name=COALESCE(?,name),file_url=COALESCE(?,file_url),category=COALESCE(?,category),status=COALESCE(?,status),updated_at=? WHERE id=? AND deleted_at IS NULL", args: [data.name || null, data.fileUrl || null, data.category || null, data.status || null, now, id] }); await writeAudit({ action: "update", entityType: resource, entityId: id, actorId: auth.session.userId }); return ok({ id }); }
    if (resource === "forms") { const data = formSchema.partial().parse(body); await db.execute({ sql: "UPDATE form_configurations SET name=COALESCE(?,name),form_type=COALESCE(?,form_type),status=COALESCE(?,status),notification_email=COALESCE(?,notification_email),updated_at=? WHERE id=? AND deleted_at IS NULL", args: [data.name || null, data.formType || null, data.status || null, data.notificationEmail || null, now, id] }); await writeAudit({ action: "update", entityType: resource, entityId: id, actorId: auth.session.userId }); return ok({ id }); }
    if (resource === "media") { const data = mediaSchema.partial().parse(body); await db.execute({ sql: "UPDATE media_assets SET filename=COALESCE(?,filename),url=COALESCE(?,url),mime_type=COALESCE(?,mime_type),alt_text=COALESCE(?,alt_text) WHERE id=? AND deleted_at IS NULL", args: [data.filename || null, data.url || null, data.mimeType || null, data.altText || null, id] }); await writeAudit({ action: "update", entityType: resource, entityId: id, actorId: auth.session.userId }); return ok({ id }); }
    if (resource === "leads") { const data = leadSchema.parse(body); await db.execute({ sql: "UPDATE leads SET status=COALESCE(?,status), assignee_id=COALESCE(?,assignee_id), tags=COALESCE(?,tags), updated_at=? WHERE id=? AND deleted_at IS NULL", args: [data.status || null, data.assigneeId === undefined ? null : data.assigneeId, data.tags ? JSON.stringify(data.tags) : null, now, id] }); if (data.note) await db.execute({ sql: "INSERT INTO lead_notes (id,lead_id,body,created_by,created_at) VALUES (?,?,?,?,?)", args: [randomUUID(), id, data.note, auth.session.userId, now] }); }
    else if (resource === "products") { const data = productSchema.partial().parse(body); await db.execute({ sql: "UPDATE products SET sku=COALESCE(?,sku),category_id=COALESCE(?,category_id),status=COALESCE(?,status),is_featured=COALESCE(?,is_featured),technical_specs=COALESCE(?,technical_specs),updated_by=?,updated_at=?,published_at=CASE WHEN ?='published' AND published_at IS NULL THEN ? ELSE published_at END WHERE id=? AND deleted_at IS NULL", args: [data.sku || null, data.categoryId || null, data.status || null, data.isFeatured === undefined ? null : data.isFeatured ? 1 : 0, data.technicalSpecs ? JSON.stringify(data.technicalSpecs) : null, auth.session.userId, now, data.status || null, now, id] }); if (data.name || data.slug || data.shortDescription !== undefined || data.content !== undefined) await db.execute({ sql: "UPDATE product_translations SET name=COALESCE(?,name),slug=COALESCE(?,slug),short_description=COALESCE(?,short_description),content=COALESCE(?,content),updated_at=? WHERE product_id=? AND locale='es'", args: [data.name || null, data.slug || null, data.shortDescription || null, data.content || null, now, id] }); }
    else if (resource === "news") { const data = newsSchema.partial().parse(body); await db.execute({ sql: "UPDATE news_articles SET category_id=COALESCE(?,category_id),status=COALESCE(?,status),is_featured=COALESCE(?,is_featured),updated_at=?,published_at=CASE WHEN ?='published' AND published_at IS NULL THEN ? ELSE published_at END WHERE id=? AND deleted_at IS NULL", args: [data.categoryId || null, data.status || null, data.isFeatured === undefined ? null : data.isFeatured ? 1 : 0, now, data.status || null, now, id] }); if (data.title || data.slug || data.excerpt !== undefined || data.content !== undefined) await db.execute({ sql: "UPDATE news_translations SET title=COALESCE(?,title),slug=COALESCE(?,slug),excerpt=COALESCE(?,excerpt),content=COALESCE(?,content),updated_at=? WHERE article_id=? AND locale='es'", args: [data.title || null, data.slug || null, data.excerpt || null, data.content || null, now, id] }); }
    else if (resource === "categories") { const data = categorySchema.partial().parse(body); if (data.parentId === id) return fail("分类不能设置自己为父级。"); await db.execute({ sql: "UPDATE product_categories SET name=COALESCE(?,name),slug=COALESCE(?,slug),parent_id=COALESCE(?,parent_id),description=COALESCE(?,description),sort_order=COALESCE(?,sort_order),is_enabled=COALESCE(?,is_enabled),show_in_nav=COALESCE(?,show_in_nav),updated_at=? WHERE id=? AND deleted_at IS NULL", args: [data.name || null, data.slug || null, data.parentId || null, data.description || null, data.sortOrder ?? null, data.enabled === undefined ? null : data.enabled ? 1 : 0, data.showInNav === undefined ? null : data.showInNav ? 1 : 0, now, id] }); }
    else return fail("该资源暂不支持修改操作。", 405);
    await writeAudit({ action: "update", entityType: resource, entityId: id, actorId: auth.session.userId }); return ok({ id });
  } catch (error) { if (error instanceof z.ZodError) return fail("提交数据校验失败。", 400, error.flatten().fieldErrors); return fail("更新失败。", 400); }
}

export async function DELETE(request: Request, context: RouteContext<"/api/admin/[resource]">) {
  const { resource } = await context.params; if (!isResource(resource)) return fail("未知的后台资源。", 404);
  const auth = await requireAdmin(resourcePermission[resource].remove); if ("response" in auth) return auth.response;
  const id = idFrom(request); if (!id) return fail("缺少记录标识。", 400);
  try {
    const db = await getDatabase(); const now = new Date().toISOString();
    if (resource === "media") await db.execute({ sql: "UPDATE media_assets SET deleted_at=? WHERE id=?", args: [now, id] });
    else if (resource === "pages") await db.execute({ sql: "UPDATE site_pages SET deleted_at=?,updated_at=? WHERE id=?", args: [now, now, id] });
    else if (resource === "downloads") await db.execute({ sql: "UPDATE download_assets SET deleted_at=?,updated_at=? WHERE id=?", args: [now, now, id] });
    else if (resource === "forms") await db.execute({ sql: "UPDATE form_configurations SET deleted_at=?,updated_at=? WHERE id=?", args: [now, now, id] });
    else if (resource === "products") await db.execute({ sql: "UPDATE products SET deleted_at=?,status='archived',updated_at=? WHERE id=?", args: [now, now, id] });
    else if (resource === "news") await db.execute({ sql: "UPDATE news_articles SET deleted_at=?,status='archived',updated_at=? WHERE id=?", args: [now, now, id] });
    else if (resource === "categories") await db.execute({ sql: "UPDATE product_categories SET deleted_at=?,updated_at=? WHERE id=?", args: [now, now, id] });
    else if (resource === "leads") await db.execute({ sql: "UPDATE leads SET deleted_at=?,updated_at=? WHERE id=?", args: [now, now, id] });
    else return fail("该资源不支持删除操作。", 405);
    await writeAudit({ action: "soft_delete", entityType: resource, entityId: id, actorId: auth.session.userId }); return ok({ id });
  } catch { return fail("删除操作失败。", 500); }
}
