import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { chileProducts, chileSolutions } from "@/lib/chile-content";
import { JsonLd, SiteFooter, SiteHeader } from "@/components/site-shell";

export function generateStaticParams() { return chileSolutions.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const solution = chileSolutions.find((item) => item.slug === slug); if (!solution) return {}; return { title: solution.title, description: solution.intro, alternates: { canonical: `/es/soluciones/${solution.slug}` }, openGraph: { title: solution.title, description: solution.intro, images: ["/assets/grimm-fire-pump-hero.png"] } }; }
export default async function SolutionDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const solution = chileSolutions.find((item) => item.slug === slug); if (!solution) notFound(); const products = chileProducts.filter((item) => solution.products.includes(item.slug)); const url = `https://grimmfirepump.cl/es/soluciones/${solution.slug}`; return <main><SiteHeader/><JsonLd data={{ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Inicio", item: "https://grimmfirepump.cl/es" }, { "@type": "ListItem", position: 2, name: "Soluciones", item: "https://grimmfirepump.cl/es/soluciones" }, { "@type": "ListItem", position: 3, name: solution.name, item: url }] }}/><section className="section shaded"><div className="shell article-layout"><p className="eyebrow">SOLUCIÓN · {solution.name.toUpperCase()}</p><h1 className="page-title">{solution.title}</h1><p className="page-intro">{solution.intro}</p><section><h2>Condiciones y foco de revisión</h2><p>{solution.challenge}</p></section><section><h2>Cómo organizar la conversación técnica</h2><p>{solution.deployment}</p></section><section><h2>Información que conviene preparar</h2><ul>{solution.inputs.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h2>Productos relacionados</h2><div className="related-links">{products.map((product) => <Link key={product.slug} href={`/es/productos/${product.slug}`}>{product.name} →</Link>)}</div></section><section className="faq-section"><h2>Preguntas frecuentes</h2>{solution.faq.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section><Link className="btn" href={`/es/contacto?solucion=${solution.slug}`}>Solicitar revisión del proyecto →</Link></div></section><SiteFooter/></main>; }
