import { notFound } from "next/navigation";
import Image from "next/image";
import { LeadForm } from "@/components/lead-form";
import { getPublicProducts } from "@/lib/public-catalog";
import { siteConfig, type Locale } from "@/lib/site-config";

export function generateStaticParams() { return siteConfig.supportedLocales.map((locale) => ({ locale })); }
export const dynamic = "force-dynamic";
export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!siteConfig.supportedLocales.includes(locale as Locale)) notFound();
  const activeLocale = locale as Locale;
  const products = await getPublicProducts();
  return <main>
    <div className="topbar"><div className="shell topbar-inner"><span>Soporte de ingeniería para proyectos en Sudamérica</span><a href={siteConfig.whatsappUrl} target="_blank" rel="noreferrer">WhatsApp {siteConfig.whatsapp} ↗</a></div></div>
    <header className="header"><div className="shell nav"><a className="brand" href={`/${locale}`}><span className="brand-mark"><i/><i/><i/></span><span>GRIMM <b>PUMP</b><small>SISTEMAS CONTRA INCENDIO</small></span></a><nav className="menu"><a href="#productos">Productos</a><a href="#soluciones">Soluciones</a><a href="#proceso">Para proyectos</a><a href="#empresa">Empresa</a><a href="#contacto">Contacto</a></nav><a className="btn btn-small" href="#contacto">Solicitar cotización →</a></div></header>
    <section className="hero"><Image src="https://raw.githubusercontent.com/shagaofeng-rgb/grimmfirepump.cl/main/public/assets/grimm-fire-pump-hero.png" alt="Sistema de bomba contra incendio en una sala industrial" fill priority sizes="100vw" /><div className="hero-overlay"/><div className="shell hero-content"><p className="eyebrow light">GRIMM PUMP · SUDAMÉRICA</p><h1>Protección contra incendio<br/><em>lista para su proyecto.</em></h1><p className="hero-copy">Paquetes de bombeo eléctrico, diésel y jockey configurados para edificios industriales, logística, infraestructura y proyectos EPC.</p><div className="hero-buttons"><a className="btn" href="#contacto">Hable con un ingeniero →</a><a className="text-link light" href="#productos">Explorar sistemas ↓</a></div><div className="hero-stats"><div><b>50–2500</b><span>GPM en paquetes</span></div><div><b>6–13</b><span>bar en configuraciones EDJ</span></div><div><b>16 bar</b><span>presión máxima</span></div></div></div></section>
    <section className="section intro"><div className="shell split"><div><p className="eyebrow">PARA EQUIPOS QUE NO PUEDEN DETENERSE</p><h2>La seguridad de una instalación empieza <em>antes del envío.</em></h2></div><p>Para los equipos de ingeniería, compras y ejecución de Sudamérica, una bomba es solo una parte del sistema. GRIMM PUMP organiza cada propuesta alrededor de la configuración, la documentación técnica y el soporte que el proyecto necesita.</p></div></section>
    <section id="productos" className="section shaded"><div className="shell"><p className="eyebrow">SISTEMAS PRINCIPALES</p><h2>Elija la configuración <em>que exige su proyecto.</em></h2><div className="product-grid">{products.map((product, index) => <article className={`product-card ${index === 0 ? "featured" : ""}`} key={product.slug}><p className="card-index">0{index + 1} / {product.category.toUpperCase()}</p><h3>{product.name}</h3><p>{product.description}</p><dl>{product.specs.map(([term, definition]) => <div key={term}><dt>{term}</dt><dd>{definition}</dd></div>)}</dl><a href="#contacto" className="card-link">Consultar configuración ↗</a></article>)}</div></div></section>
    <section id="soluciones" className="section"><div className="shell"><p className="eyebrow">APLICACIONES</p><h2>Configuradas para la realidad <em>de cada instalación.</em></h2><div className="application-list">{[["Centros logísticos y bodegas","Rociadores, presión estable y respuesta rápida."],["Plantas industriales","Sistemas configurados para talleres, proceso y servicios."],["Centros de datos","Respaldo para infraestructura de misión crítica."],["Petróleo, gas y sitios remotos","Configuraciones diésel para entornos exigentes."]].map(([title,description],index)=><a href="#contacto" key={title}><span>0{index+1}</span><b>{title}<small>{description}</small></b><i>→</i></a>)}</div></div></section>
    <section id="proceso" className="section dark"><div className="shell"><p className="eyebrow light">UNA RUTA CLARA PARA COMPRAS</p><h2>Datos técnicos que ayudan a decidir <em>con certeza.</em></h2><div className="process-grid">{[["Comparta la condición","Caudal, presión, fuente de energía y tipo de instalación."],["Revise la propuesta","Orientación sobre la configuración adecuada."],["Valide la documentación","Catálogo, modelos e información técnica para revisión."],["Coordine su entrega","Defina los siguientes pasos con comunicación directa."]].map(([title,description],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
    <section id="empresa" className="section"><div className="shell split company"><div><p className="eyebrow">EL RESPALDO DE GRIMM</p><h2>Fabricación, ensamblaje y documentación <em>en una misma conversación.</em></h2><p>GRIMM PUMP es la marca orientada a exportación de Grimm Water Treatment (Zhejiang) Co., Ltd. para compradores que buscan información técnica, sistemas configurados y una respuesta directa.</p></div><div className="evidence"><article><b>◎</b><h3>Paquetes integrados</h3><p>EDJ, diésel + jockey y eléctrico + jockey.</p></article><article><b>▦</b><h3>Datos de selección</h3><p>Rangos y configuraciones para la conversación técnica.</p></article><article><b>✓</b><h3>Revisión documental</h3><p>Catálogos, datos de bomba y evidencia de pruebas.</p></article><article><b>↗</b><h3>Comunicación exportadora</h3><p>Atención directa por email o WhatsApp.</p></article></div></div></section>
    <section id="contacto" className="section contact"><div className="shell split"><div><p className="eyebrow">CONTACTO DE PROYECTO</p><h2>Envíe su requerimiento.</h2><p className="contact-lead">Comparta caudal, presión y el tipo de aplicación. Le responderemos con una orientación inicial y la información de catálogo correspondiente.</p><p><b>Email</b><br/><a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a></p><p><b>WhatsApp</b><br/><a href={siteConfig.whatsappUrl}>{siteConfig.whatsapp}</a></p><p><b>Dirección</b><br/>{siteConfig.address}</p></div><LeadForm locale={activeLocale}/></div></section>
    <footer><div className="shell footer"><a className="brand" href={`/${locale}`}><span className="brand-mark"><i/><i/><i/></span><span>GRIMM <b>PUMP</b><small>SISTEMAS CONTRA INCENDIO</small></span></a><p>© {new Date().getFullYear()} {siteConfig.legalCompanyName}</p><p>Proyecto independiente para Sudamérica · versión local</p></div></footer>
  </main>;
}
